config/routes.rb
Afterclassroom::Application.routes.draw do
  resources :omnitauths

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  # RESTful rewrites
	match '/login' => 'sessions#new', :as => :login
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/logout' => 'sessions#destroy', :as => :logout, :conditions => {:method => :delete}

  match '/users/troubleshooting' => 'users#troubleshooting', :as => :user_troubleshooting
  match '/users/forgot_password' => 'users#forgot_password', :as => :user_forgot_password
  match '/users/reset_password/:password_reset_code' => 'users#reset_password', :as => :user_reset_password
  match '/users/forgot_login' => 'users#forgot_login', :as => :user_forgot_login
  match '/users/clueless' => 'users#clueless', :as => :user_clueless
  
  # Users
  resources :users do
    member do
      get :edit_password, :edit_email, :show_lounge, :show_stories, :show_story_detail, :show_photos, :show_photos_with_list, :show_photo_album, :show_photo_detail, :show_musics, :show_music_album, :show_videos, :show_detail_video, :show_friends, :show_fans, :warning, :warning_media,
        :list_friend_to_tag
      put :update_password, :update_email
      post :update_avatar, :remove_tagged, :add_tag, :tag_decision
    end
	
    #Messages
    resources :messages do
      collection do
        get :show_email, :list_friend, :delete_message
        post :message_action, :send_message
      end
    end
   
    #Learning tools
    resources :learn_tools do
      collection do
        get :index, :featured_tool_paging, :maylike_tool_paging, 
          :first_tab_paging, :search_tool, :see_all_tool_fan, :contact_dev_form, 
          :mylearn, :tool_rev_paging, :write_review_form, :become_a_fan,
          :new_tool, :verify_handler, :owner_handler, :video_list, :video_list_paging,
          :rate, :new_tool_with_api, :choose_to_add, :edit_review_form, :delete_review,
          :play_vid, :toolmanager, :edit_tool, :delete_tool, :fan_list_paging, :view_review,
          :add_mytool, :delete_fans
        post :submit_review, :submit_new_tool, :create_tool_with_api, 
          :send_to_dev,:update_review, :save_edit_tool
      end
    end    
    
    #Settings
    resources :settings do
      collection do
        get :networks, :notifications, :language,
          :payments, :ads, :setting, :private,
          :change_psw, :save_psw, :change_name,
          :save_name, :change_user_name, :save_user_name,
					:change_email, :save_email,
          :change_time_zone, :save_time_zone, :blocks, :unblock,
					:change_school, :save_school,
					:change_chat_id, :change_chat_yahoo_id, :save_chat_id
        post :save_setting, :save_private_setting, :check_login
      end
    end
 
    #Profiles
    resources :profiles do
      collection do
        get :show_profile, :edit_infor, :edit_edu_infor,
          :edit_work_infor, :my_favorite, :fan, :delete_fans, :delete_prof
        post :update_about_yourself, :update_infor, :update_edu_infor, :update_work_infor
      end
    end
    
    #Student lounges
    resources :student_lounges do
      collection do
        get :chat, :invite_chat, :add_users_to_chat, :stop_chat, :chanel_chat_content,
          :friends_changed_message, :friends_you_invited_chat, :friends_want_you_chat, :friends_online
        post :send_data
      end
    end

    #Friends
    resources :friends do
      collection do
        get :search, :search_suggestion, :find, :find_people, :recently_added, :recently_updated,
          :friend_request, :list, :invite, :unfriend, :display_email, :add_to_group,
          :send_invite_message, :show_invite, :become_a_fan, :accept, :de_accept, :respond_to_friend_request, :get_suggestion_list
        post :find_email, :invite_by_list_email,
          :invite_by_import_email, :delete, :show_list_email_contacts,
					:find_friend_by_email
      end
    end
	
    #Stories
    resources :stories do
      collection do
        get :friend_s, :my_s, :my_draft, :draft, :create_comment, :delete_comment, :delete_all, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    # Music Album
    resources :music_albums do
      collection do
        get :delete_all, :delete_musics, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :musics do
      collection do
        get :friend_m, :my_m, :create_playlist, :create_form, :play_list
        post :create_album, :upload
      end
    end

    # Photo Album
    resources :photo_albums do
      collection do
        get :delete_all, :delete_photos
      end
    end
    
    # Videos
    resources :videos do
      collection do
        get :friend_p, :my_p, :create_form, :delete_videos, :update_video, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :photos do
      collection do
        get :friend_p, :my_p, :create_form, :destroy_all, :show_album, :show_album_with_list, :phototag, :deletetag, :addtag, :usrdata, :self_untag
        post :create_album, :upload, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    resources :u_forums do
      collection do
        get :dft_stgs, :post_lounge, :item_setting, :post_lounge_b, :rate, :friend_pad, :find_people, 
        :select_share, :page_share, :add_usr, :remove_usr, :page_member, :add_usr_show, :page_share_show, :remove_usr_show, 
        :friend_pad_show, :find_people_show, :unsubscribe, :del_cmt, :subscribe
        post :save_setting, :save_custom, :save_cmt, :save_custom_b, :remove_member, :add_more_member
      end
      
    end

    # Youtube
    resources :youtubes do
      new do
        post :upload
      end

      collection do
        get :authorise
      end
    end
  
    # Post managements
    resources :post_managements do
      collection do
        get :with_type, :delete_all
      end
    end
    
    # Share files
    resources :shares
  end

  # Sessions
  resource :session do
    collection do
      get :change_school
    end
  end

  # State
  resources :states

  # City
  resources :cities do 
    collection do
      get :state
    end
  end

  #Rate comment 
  resources :rate_cmts do
    collection do
      get :load_bk_like, :load_bk_dislike, :load_other
      post :add_like_cmt, :add_like_cmt
    end
  end    


  # School
  resources :schools do
    collection do
      get :state_or_city, :city
    end
  end

  # Posts
  resources :posts do
    collection do
      get :report_abuse, :create_report_abuse, :report_abuse_video, :create_report_abuse_video, :delete_comment, :download, :view_all_comments, :report_abuse_vid, :comments_list, :remove_attach_file
      post :create_comment_on_list, :create_comment
    end
  end

  resources :post_assignments do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_projects do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_tests do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end
  
  resources :post_exams do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_events do
    collection do
      get :search, :tag, :rate
    end
  end

  resources :post_qas do
    collection do
      get :search, :tag, :interesting, :top_answer, :create_comment, :rate, :require_rate, :prefer, :sendmail
    end
  end

  resources :post_tutors do
    collection do
      get :search, :tag, :effective, :dont_hire, :rate, :require_rate
    end
  end

  resources :post_books do
    collection do
      get :search, :tag, :good_books, :dont_buy, :rate, :require_rate
    end
  end

  resources :post_jobs do
    collection do
      get :search, :tag, :good_companies, :bad_bosses,
        :rate, :require_rate, :my_job_list, :add_job,
        :employment_infor, :show_job_infor, :apply_job,
        :save_letter, :save_script, :save_resume, :delete_job_list
    end
  end

  resources :post_foods do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_parties do
    collection do
      get :search, :show_rsvp, :create_rsvp,
        :tag, :rate, :require_rate,
        :prefer, :my_party_list, :add_party, :delete_party_list, :sendmail
    end
  end

  resources :post_myxes do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_awarenesses do
    collection do
      get :search, :tag, :rate, :support, :require_rate
    end
  end

  resources :post_housings do
    collection do
      get :search, :tag, :good_house, :worse_house, :rate
    end
  end

  resources :post_teamups do
    collection do
      get :search, :tag, :good_org, :worse_org, :more_startup, :rate
    end
  end

  # Exam/Test Schedules, Deadline bulletin, General bulletin
  resources :post_exam_schedules do
    collection do
      get :search, :tag, :rate
    end
  end
  
    resources :post_lecture_notes do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end
  
  #Ajax not login
  resources :ajax_not_login do
    collection do
      get :show_comment, :rate_comment, :rate_comment_action, :view_results, :view_press_info_detail, :view_career_detail
    end
  end
  
  # Feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  # Tags
  resources :tags do
    collection do
      get :show_tags, :show_tags_list
    end
  end
  
  #Simple Captcha
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  
  #Forums
  resources :forums do 
    collection do

app/models/post_job.rb
# © Copyright 2009 AfterClassroom.com — All Rights Reserved
class PostJob < ActiveRecord::Base
  # Validations
  validates_presence_of :post_id

  # Relations
  belongs_to :post, :dependent => :destroy
  belongs_to :job_type
  has_one :rating_statistic
  has_many :ratings
  has_many :job_files, :dependent => :destroy
  has_many :jobs_lists, :dependent => :destroy
  
  # Tags
  acts_as_taggable_on :tags

  # Rating for Good or Bad
  acts_as_rated :rating_range => 0..1, :with_stats_table => true

  # Named Scope
  scope :with_limit, :limit => LIMIT
  scope :with_type, lambda { |tp| {:conditions => ["post_jobs.job_type_id = ?", tp], :order => "id DESC"} }
  scope :without_type, lambda { |tp| {:conditions => ["post_jobs.job_type_id <> ?", tp], :order => "id DESC"} }
  scope :with_status, lambda { |st| {:conditions => ["post_jobs.rating_status = ?", st], :order => "id DESC"} }
  scope :recent, {:joins => :post, :order => "posts.created_at DESC"}
  scope :with_school, lambda {|sc| return {} if sc.nil?; {:joins => :post, :conditions => ["school_id = ?", sc], :order => "posts.created_at DESC"}}
  scope :random, lambda { |random| {:order => "RAND()", :limit => random }}
  scope :previous, lambda { |att| {:conditions => ["post_jobs.id < ?", att], :order => "id ASC"} }
  scope :nexts, lambda { |att| {:conditions => ["post_jobs.id > ?", att], :order => "id ASC"} }

  def self.paginated_post_conditions_with_option(params, school, type_id)
    over = params[:over].to_i
    year = params[:year]
    department = params[:department]
    from_school = params[:from_school]
    with_school = school
    with_school = from_school if from_school

    post_jobs = PostJob.ez_find(:all, :include => [:post, :job_type], :order => "posts.created_at DESC") do |post_job, post, job_type|
      job_type.id == type_id
      post.department_id == department if department
      post.school_year == year if year
      post.school_id == with_school if with_school
      post.created_at > over.business_days.before(Time.now) if over > 0
    end

    posts = []
    post_jobs.select {|p| posts << p.post}
    return posts
  end

  def self.paginated_post_more_like_this(params, post_like)
    post_ts = PostJob.ez_find(:all, :include => [:post, :job_type], :order => "posts.created_at DESC") do |post_job, post, job_type|
      job_type.id == post_like.post_job.job_type_id
      post.department_id == post_like.department_id
      post.school_year == post_like.school_year
      post.school_id == post_like.school_id
    end

    posts = []
    post_ts.select {|p| posts << p.post}
    return posts
  end
  
  def self.paginated_post_conditions_with_tag(params, school, tag_name)
    arr_p = []
    post_as = self.with_school(school).tagged_with(tag_name)
    post_as.select {|p| arr_p << p.post}
    @posts = arr_p.paginate :page => params[:page], :per_page => 10
  end

  def self.paginated_post_conditions_with_good_companies(params, school)
    posts = []
    post_as = self.good_companies(school)
    post_as.select {|p| posts << p.post}
    posts.paginate :page => params[:page], :per_page => 10
  end

  def self.paginated_post_conditions_with_bad_bosses(params, school)
    posts = []
    post_as = self.bad_bosses(school)
    post_as.select {|p| posts << p.post}
    posts.paginate :page => params[:page], :per_page => 10
  end

  def self.related_posts(school, type)
    posts = []
    post_as = self.random(5).with_school(school).with_type(type)
    post_as.select {|p| posts << p.post}
    posts
  end

  def self.good_companies(school)
    type = JobType.find_by_label("i_m_looking_for_job")
    post_jobs = self.with_school(school).without_type(type.id).with_status("Good")
  end

  def self.bad_bosses(school)
    type = JobType.find_by_label("i_m_looking_for_job")
    post_jobs = self.with_school(school).without_type(type.id).with_status("Bad")
  end

  def self.require_rating(school)
    post_jobs = self.with_school(school).with_status("Require Rating").random(1)
  end
  
  def total_good
    self.ratings.count(:conditions => ["rating = ?", 1])
  end

  def total_bad
    self.ratings.count(:conditions => ["rating = ?", 0])
  end

  def score_good
    total = self.total_good + self.total_bad
    (total) == 0 ? 0 : (self.total_good.to_f/(total))*100
  end

  def score_bad
    total = self.total_good + self.total_bad
    (total) == 0 ? 0 : (self.total_bad.to_f/(total))*100
  end
end

app/views/post_jobs/_bad_bosses.html.erb
<div class="col195 jobBad">
  <div class="col195in">
    <h1 class="col195Title">Bad bosses</h1>
    <div class="col195Cont">
      <%
      bad_bosses = PostJob.with_limit.bad_bosses(@school)
    %>
      <% if bad_bosses.size > 0 %>
        <%
        bad_bosses.each do |tt|
        %>
          <div class="dueDItem">
            <div class="dueDTitle"><%= link_to truncate_words(tt.post.title, 4), post_job_path(tt) %></div>
          </div>
        <% end %>
		<% if bad_bosses.size > LIMIT - 1 %>
        <div class="dueDbutton"><%= link_to "View more Bad bosses", bad_bosses_post_jobs_path %></div>
		<% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/post_jobs/_my_jobs_list.html.erb
<% if logged_in? %>
  <div class="col195 jobGood">
    <div class="col195in">
      <h1 class="col195Title">My jobs list</h1>
      <div class="col195Cont">
        <%
        jobs_lists = current_user.jobs_lists.order("created_at DESC").limit(LIMIT) %>
        <% if jobs_lists.size > 0 %>
          <%
          count = 0
          jobs_lists.each do |jl| %>
            <% if jl.post_job %>
              <div class="dueDItem">
                <div class="dueDTitle">
                  <%= link_to truncate_words(jl.post_job.post.title, 4), post_job_path(jl.post_job) %>
                </div>
              </div>
              <% count = count + 1%>
            <% end %>
          <% end %>
          <% if count == LIMIT %>
            <div class="dueDbutton">
              <%= link_to "View more my jobs list", "#{my_job_list_post_jobs_path}?height=400&width=470", :class => "thickbox" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/post_jobs/_poll.html.erb
<%
post_job = PostJob.require_rating(@school).first
%>
<% if post_job %>
  <div class="col195 QAsPoll">
    <div class="col195in">
      <h1 class="col195Title">Poll this Job</h1>
      <div class="col195Cont">
        <div class="QAsPCont">
          <p><%= link_to post_job.post.title, post_job %></p>
          <p><%= truncate_words(post_job.post.description) %></p>
        </div>
        <div id="require_rating_action">
          <div class="QAsDet"><input type="radio" name="rating" value="1" checked="checked"/><span>Good</span><strong rel="rate" style="display:none;">(<%= post_job.total_good %>)</strong></div>
          <div class="QAsDet"><input type="radio" name="rating" value="0"/><span>Bad</span><strong rel="rate" style="display:none;">(<%= post_job.total_bad %>)</strong></div>
          <div class="submit"><%= show_submit_rating(post_job.post.id, require_rate_post_jobs_path) %></div>
          <div class="PollView" id="view_results">[<a href="javascript:;" onclick="showResult();">View results</a>]</div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/post_jobs/bad_bosses.html.erb
<% content_for :you_are_here do -%>
  You are here: <a href="/">Home</a><%= link_to "Jobs", post_jobs_path, :class => "abLink-detail" %><%= link_to "Bad bosses", "#", :class => "abLink-detail" %>
<% end -%>

<% content_for :post_button do -%>
  <%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>

<% content_for :menu_sub do -%>
  <%= render :partial => "submenu" %>
<% end -%>

<!--Content-->
<div class="contMainL">
  <div class="col451 Book">
    <div class="col451in">
      <div class="AsDTop">
        <h1 class="titleH1">Bad bosses</h1>
        <div class="AsDsearch">
          <%= render :partial => "shared/search_indetail", :locals => {:url_search => search_post_jobs_path} %>
        </div>
      </div>
      <div class="col451Cont">
        <%= display_flash_messages_with_raw %>

        <!--List Items-->
        <% @posts.each do |post| %>
          <div id="post_<%= post.id %>"><%= render :partial => "item", :locals => {:post => post, :title => post.title, :description => post.description, :controller_name => controller.controller_name} %></div>
        <% end %>
        <!--List Items-->

        <!--Pagination-->
        <div class="assPage">
          <span class="numPage"><%= page_entries_info @posts %></span>
          <%= will_paginate @posts %>
        </div>
        <!--Pagination-->
        <div class="goTop"><a href="javascript:;" onclick="goToByScroll('top_page')">Top</a></div>
      </div>
    </div>
  </div>

</div>
<div class="contMainC">
  <!--Browser Bad Bosses-->
  <%= render :partial => "bad_bosses" %>
  <!--Browser Bad Bosses-->

  <!--Browser Good Companies-->
  <%= render :partial => "good_companies" %>
  <!--Browser Good Companies-->

  <!--Browser Employement Info-->
  <%= render :partial => "employment_info" %>
  <!--Browser Employement Info-->
</div>

<div class="contMainR">
  <!--Browser by Subject-->
  <%= render :partial => "shared/browser_by_subject" %>
  <!--Browser by Subject-->

  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->

  <!--Request Assignment-->
  <%= render :partial => "form_request_job" %>
  <!--Request Assignment-->

  <!--Recent Request Assignments-->
  <%= render :partial => "recent_request_jobs" %>
  <!--Recent Request Assignments-->
</div>
<!--Content-->

app/views/post_jobs/employment_infor.html.erb
<% content_for :you_are_here do -%>
  You are here: <a href="/">Home</a><%= link_to "Jobs", post_jobs_path, :class => "abLink-detail" %><%= link_to "Employment information", "#", :class => "abLink-detail" %>
<% end -%>

<% content_for :post_button do -%>
  <%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>

<% content_for :menu_sub do -%>
  <%= render :partial => "submenu" %>
<% end -%>

<!--Content-->
<div class="contMainL">
  <div class="col451 Book">
    <div class="col451in">
      <div class="AsDTop">
        <h1 class="titleH1">Employment information</h1>
      </div>
      <div class="col451Cont">

        <%= display_flash_messages_with_raw %>
        
        <!--List Items-->
        <% @job_infors.each do |j| %>
          <div class="assItem">
            <div class="assItemL">
              <div class="assContT" style="float:left">
                <h2 class="titleH2"><%= link_to j.title, show_job_infor_post_jobs_path(:job_infor_id => j.id) %></h2>
              </div>
              <div class="assDes"><%= truncate_words(j.description) %></div>
            </div>
            <div class="assItemB">
              <div class="assInfT">
                <div class="assInfT">
                  <div class="assInfR"><%= link_to "more", show_job_infor_post_jobs_path(:job_infor_id => j.id) %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <!--List Items-->

        <!--Pagination-->
        <div class="assPage">
          <span class="numPage"><%= page_entries_info @job_infors %></span>
          <%= will_paginate @job_infors %>
        </div>
        <!--Pagination-->
        <div class="goTop"><a href="javascript:;" onclick="goToByScroll('top_page')">Top</a></div>
      </div>
    </div>
  </div>

</div>
<div class="contMainC">
  <!--Browser Bad Bosses-->
  <%= render :partial => "bad_bosses" %>
  <!--Browser Bad Bosses-->

  <!--Browser Good Companies-->
  <%= render :partial => "good_companies" %>
  <!--Browser Good Companies-->

  <!--Browser Employement Info-->
  <%= render :partial => "employment_info" %>
  <!--Browser Employement Info-->
</div>

<div class="contMainR">
  <!--Browser by Subject-->
  <%= render :partial => "shared/browser_by_subject" %>
  <!--Browser by Subject-->

  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->

  <!--Request Job-->
  <%= render :partial => "form_request_job" %>
  <!--Request Job-->

  <!--Recent Request Jobs-->
  <%= render :partial => "recent_request_jobs" %>
  <!--Recent Request Jobs-->
</div>
<!--Content-->

app/views/post_jobs/index.html.erb
<% content_for :you_are_here do -%>
  You are here: <a href="/">Home</a><%= link_to "Jobs", post_jobs_path, :class => "abLink-detail" %>
<% end -%>

<% content_for :post_button do -%>
  <%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>

<% content_for :menu_sub do -%>
  <%= render :partial => "submenu" %>
<% end -%>

<!--Content-->
<div class="contMainL">
  <div class="col451 Book">
    <div class="col451in">
      <div class="col451Cont">

        <%= display_flash_messages_with_raw %>
        
        <!--Options-->
        <%= show_options(@school, params, {"job_type_id" => @job_type_id}) %>
        <!--Options-->

        <!--List Items-->
        <% @posts.each do |post| %>
          <div id="post_<%= post.id %>"><%= render :partial => "item", :locals => {:post => post, :title => post.title, :description => post.description, :controller_name => controller.controller_name} %></div>
        <% end %>
        <!--List Items-->

        <!--Pagination-->
        <div class="assPage">
          <span class="numPage"><%= page_entries_info @posts %></span>
          <%= will_paginate @posts %>
        </div>
        <!--Pagination-->
        <div class="goTop"><a href="javascript:;" onclick="goToByScroll('top_page')">Top</a></div>
      </div>
    </div>
  </div>

</div>
<div class="contMainC">
  <!--Browser Bad Bosses-->
  <%= render :partial => "bad_bosses" %>
  <!--Browser Bad Bosses-->

  <!--Browser Good Companies-->
  <%= render :partial => "good_companies" %>
  <!--Browser Good Companies-->
	
	<!--My jobs list-->
  <%= render :partial => "my_jobs_list" %>
  <!--My jobs list-->
	
  <!--Browser Employement Info-->
  <%= render :partial => "employment_info" %>
  <!--Browser Employement Info-->
  <!--Browser Poll this Tutors-->
  <%= render :partial => "poll" %>
  <!--Browser Poll this Tutors-->
</div>

<div class="contMainR">
  <!--Browser by Subject-->
  <%= render :partial => "shared/browser_by_subject" %>
  <!--Browser by Subject-->

  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->

  <!--Request Assignment-->
  <%= render :partial => "form_request_job" %>
  <!--Request Assignment-->

  <!--Recent Request Assignments-->
  <%= render :partial => "recent_request_jobs" %>
  <!--Recent Request Assignments-->
</div>
<!--Content-->

app/views/post_jobs/show_job_infor.html.erb
<% content_for :you_are_here do -%>
  You are here: <a href="/">Home</a><%= link_to "Jobs", post_jobs_path, :class => "abLink-detail" %><%= link_to "Employment information", employment_infor_post_jobs_path, :class => "abLink-detail" %><%= link_to "Detail", "#", :class => "abLink-detail" %>
<% end -%>

<% content_for :post_button do -%>
  <%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>

<% content_for :menu_sub do -%>
  <%= render :partial => "submenu" %>
<% end -%>

<!--Content-->
<div class="contDetL">
  <div class="contDetLin JobDetail">
    <div class="AsDTop">
      <h1 class="titleH1">Employment information detail</h1>
    </div>
    <div class="AsDCont">
      <%= display_flash_messages_with_raw %>
      <div class="AsDContL">
        <h2 class="titleH2"><%= @job_infor.title %></h2>
        <div class="AsDContLdes"><span>Description:</span><%= @job_infor.description %></div>
      </div>
      <div class="AsDContBtm">
        <span class="btmCom"><a href="javascript:;" onclick="$('#form_comment').toggle('slow');"><span>Comment</span></a></span>
        <span class="btmShare"><%= addthis_bookmark_button { "<span>Share</span>" } %></span>
      </div>
    </div>
    <div>
      <%= show_post_comments(@job_infor) %>
    </div>
    <div class="goback" id="go_back">
      <%= show_go_back %>
    </div>
    <div class="comPage">
      <span></span>
      <span class="compre"><%= link_to "", show_job_infor_post_jobs_path(:job_infor_id => @prev.id) if @prev %> </span>
      <span class="comnext"><%= link_to "", show_job_infor_post_jobs_path(:job_infor_id => @next.id) if @next %></span>
      <% if @job_infor.attach_file_name %>
        <span class="btmDown"><a href="javascript:downloadFile('<%= @job_infor.attach.url %>')" class="downarrow"><span>Download</span></a></span>
      <% end %>
    </div>
    <div class="goTop"><a href="javascript:;" onclick="goToByScroll('top_page')">Top</a></div>
  </div>
</div>	

<div class="contMainR">
  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->

  <!--Recent Request Jobs-->
  <%= render :partial => "recent_request_jobs" %>
  <!--Recent Request Jobs-->
</div>
<!--Content-->