config/routes.rb
Afterclassroom::Application.routes.draw do
  resources :omnitauths

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  # RESTful rewrites
	match '/login' => 'sessions#new', :as => :login
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/logout' => 'sessions#destroy', :as => :logout, :conditions => {:method => :delete}

  match '/users/troubleshooting' => 'users#troubleshooting', :as => :user_troubleshooting
  match '/users/forgot_password' => 'users#forgot_password', :as => :user_forgot_password
  match '/users/reset_password/:password_reset_code' => 'users#reset_password', :as => :user_reset_password
  match '/users/forgot_login' => 'users#forgot_login', :as => :user_forgot_login
  match '/users/clueless' => 'users#clueless', :as => :user_clueless
  
  # Users
  resources :users do
    member do
      get :edit_password, :edit_email, :show_lounge, :show_stories, :show_story_detail, :show_photos, :show_photos_with_list, :show_photo_album, :show_photo_detail, :show_musics, :show_music_album, :show_videos, :show_detail_video, :show_friends, :show_fans, :warning, :warning_media,
        :list_friend_to_tag
      put :update_password, :update_email
      post :update_avatar, :remove_tagged, :add_tag, :tag_decision
    end
	
    #Messages
    resources :messages do
      collection do
        get :show_email, :list_friend, :delete_message
        post :message_action, :send_message
      end
    end
   
    #Learning tools
    resources :learn_tools do
      collection do
        get :index, :featured_tool_paging, :maylike_tool_paging, 
          :first_tab_paging, :search_tool, :see_all_tool_fan, :contact_dev_form, 
          :mylearn, :tool_rev_paging, :write_review_form, :become_a_fan,
          :new_tool, :verify_handler, :owner_handler, :video_list, :video_list_paging,
          :rate, :new_tool_with_api, :choose_to_add, :edit_review_form, :delete_review,
          :play_vid, :toolmanager, :edit_tool, :delete_tool, :fan_list_paging, :view_review,
          :add_mytool, :delete_fans
        post :submit_review, :submit_new_tool, :create_tool_with_api, 
          :send_to_dev,:update_review, :save_edit_tool
      end
    end    
    
    #Settings
    resources :settings do
      collection do
        get :networks, :notifications, :language,
          :payments, :ads, :setting, :private,
          :change_psw, :save_psw, :change_name,
          :save_name, :change_user_name, :save_user_name,
					:change_email, :save_email,
          :change_time_zone, :save_time_zone, :blocks, :unblock,
					:change_school, :save_school,
					:change_chat_id, :change_chat_yahoo_id, :save_chat_id
        post :save_setting, :save_private_setting, :check_login
      end
    end
 
    #Profiles
    resources :profiles do
      collection do
        get :show_profile, :edit_infor, :edit_edu_infor,
          :edit_work_infor, :my_favorite, :fan, :delete_fans, :delete_prof
        post :update_about_yourself, :update_infor, :update_edu_infor, :update_work_infor
      end
    end
    
    #Student lounges
    resources :student_lounges do
      collection do
        get :chat, :invite_chat, :add_users_to_chat, :stop_chat, :chanel_chat_content,
          :friends_changed_message, :friends_you_invited_chat, :friends_want_you_chat, :friends_online
        post :send_data
      end
    end

    #Friends
    resources :friends do
      collection do
        get :search, :search_suggestion, :find, :find_people, :recently_added, :recently_updated,
          :friend_request, :list, :invite, :unfriend, :display_email, :add_to_group,
          :send_invite_message, :show_invite, :become_a_fan, :accept, :de_accept, :respond_to_friend_request, :get_suggestion_list
        post :find_email, :invite_by_list_email,
          :invite_by_import_email, :delete, :show_list_email_contacts,
					:find_friend_by_email
      end
    end
	
    #Stories
    resources :stories do
      collection do
        get :friend_s, :my_s, :my_draft, :draft, :create_comment, :delete_comment, :delete_all, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    # Music Album
    resources :music_albums do
      collection do
        get :delete_all, :delete_musics, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :musics do
      collection do
        get :friend_m, :my_m, :create_playlist, :create_form, :play_list
        post :create_album, :upload
      end
    end

    # Photo Album
    resources :photo_albums do
      collection do
        get :delete_all, :delete_photos
      end
    end
    
    # Videos
    resources :videos do
      collection do
        get :friend_p, :my_p, :create_form, :delete_videos, :update_video, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :photos do
      collection do
        get :friend_p, :my_p, :create_form, :destroy_all, :show_album, :show_album_with_list, :phototag, :deletetag, :addtag, :usrdata, :self_untag
        post :create_album, :upload, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    resources :u_forums do
      collection do
        get :dft_stgs, :post_lounge, :item_setting, :post_lounge_b, :rate, :friend_pad, :find_people, 
        :select_share, :page_share, :add_usr, :remove_usr, :page_member, :add_usr_show, :page_share_show, :remove_usr_show, 
        :friend_pad_show, :find_people_show, :unsubscribe, :del_cmt, :subscribe
        post :save_setting, :save_custom, :save_cmt, :save_custom_b, :remove_member, :add_more_member
      end
      
    end

    # Youtube
    resources :youtubes do
      new do
        post :upload
      end

      collection do
        get :authorise
      end
    end
  
    # Post managements
    resources :post_managements do
      collection do
        get :with_type, :delete_all
      end
    end
    
    # Share files
    resources :shares
  end

  # Sessions
  resource :session do
    collection do
      get :change_school
    end
  end

  # State
  resources :states

  # City
  resources :cities do 
    collection do
      get :state
    end
  end

  #Rate comment 
  resources :rate_cmts do
    collection do
      get :load_bk_like, :load_bk_dislike, :load_other
      post :add_like_cmt, :add_like_cmt
    end
  end    


  # School
  resources :schools do
    collection do
      get :state_or_city, :city
    end
  end

  # Posts
  resources :posts do
    collection do
      get :report_abuse, :create_report_abuse, :report_abuse_video, :create_report_abuse_video, :delete_comment, :download, :view_all_comments, :report_abuse_vid, :comments_list, :remove_attach_file
      post :create_comment_on_list, :create_comment
    end
  end

  resources :post_assignments do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_projects do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_tests do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end
  
  resources :post_exams do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_events do
    collection do
      get :search, :tag, :rate
    end
  end

  resources :post_qas do
    collection do
      get :search, :tag, :interesting, :top_answer, :create_comment, :rate, :require_rate, :prefer, :sendmail
    end
  end

  resources :post_tutors do
    collection do
      get :search, :tag, :effective, :dont_hire, :rate, :require_rate
    end
  end

  resources :post_books do
    collection do
      get :search, :tag, :good_books, :dont_buy, :rate, :require_rate
    end
  end

  resources :post_jobs do
    collection do
      get :search, :tag, :good_companies, :bad_bosses,
        :rate, :require_rate, :my_job_list, :add_job,
        :employment_infor, :show_job_infor, :apply_job,
        :save_letter, :save_script, :save_resume, :delete_job_list
    end
  end

  resources :post_foods do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_parties do
    collection do
      get :search, :show_rsvp, :create_rsvp,
        :tag, :rate, :require_rate,
        :prefer, :my_party_list, :add_party, :delete_party_list, :sendmail
    end
  end

  resources :post_myxes do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_awarenesses do
    collection do
      get :search, :tag, :rate, :support, :require_rate
    end
  end

  resources :post_housings do
    collection do
      get :search, :tag, :good_house, :worse_house, :rate
    end
  end

  resources :post_teamups do
    collection do
      get :search, :tag, :good_org, :worse_org, :more_startup, :rate
    end
  end

  # Exam/Test Schedules, Deadline bulletin, General bulletin
  resources :post_exam_schedules do
    collection do
      get :search, :tag, :rate
    end
  end
  
    resources :post_lecture_notes do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end
  
  #Ajax not login
  resources :ajax_not_login do
    collection do
      get :show_comment, :rate_comment, :rate_comment_action, :view_results, :view_press_info_detail, :view_career_detail
    end
  end
  
  # Feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  # Tags
  resources :tags do
    collection do
      get :show_tags, :show_tags_list
    end
  end
  
  #Simple Captcha
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  
  #Forums
  resources :forums do 
    collection do

app/helpers/friends_helper.rb
# © Copyright 2009 AfterClassroom.com — All Rights Reserved
module FriendsHelper
  def display_mailtype(mail_type)
    case mail_type
    when MailAccount::GMAIL
      "@gmail.com"
    when MailAccount::YAHOOMAIL
      "@yahoo.com"
    when MailAccount::AOL
      "@aol.com"
    when MailAccount::HOTMAIL
      hotmail_suffix = [
        ["hotmail.com", "hotmail.com"], ["hotmail.co.il", "hotmail.co.il"], ["hotmail.co.jp", "hotmail.co.jp"], ["hotmail.co.th", "hotmail.co.th"],
        ["hotmail.co.uk", "hotmail.co.uk"], ["hotmail.com.ar", "hotmail.com.ar"], ["hotmail.com.tr", "hotmail.com.tr"], ["hotmail.es", "hotmail.es"],
        ["hotmail.de","hotmail.de"], ["hotmail.fr", "hotmail.fr"], ["hotmail.it", "hotmail.it"], ["live.at", "live.at"], ["live.be", "live.be"],
        ["live.ca", "live.ca"], ["live.cl", "live.cl"], ["live.cn", "live.cn"], ["live.co.in", "live.co.in"],["live.co.kr", "live.co.kr"],
        ["live.co.uk", "live.co.uk"], ["live.co.za", "live.co.za"], ["live.com", "live.com"], ["live.com.ar", "live.com.ar"], ["live.com.au", "live.com.au"],
        ["live.com.co", "live.com.co"], ["live.com.mx", "live.com.mx"], ["live.com.my", "live.com.my"], ["live.com.pe", "live.com.pe"], ["live.com.ph", "live.com.ph"],
        ["live.com.pk", "live.com.pk"], ["live.com.pt", "live.com.pt"], ["live.com.sg", "live.com.sg"], ["live.com.ve", "live.com.ve"], ["live.de", "live.de"],
        ["live.dk", "live.dk"], ["live.fr", "live.fr"], ["live.hk", "live.hk"], ["live.ie", "live.ie"], ["live.in", "live.in"], ["live.it", "live.it"], ["live.jp", "live.jp"],
        ["live.nl", "live.nl"], ["live.no", "live.no"], ["live.ph", "live.ph"], ["live.ru", "live.ru"], ["br.live.com", "br.live.com"], ["live.se", "live.se"],
        ["livemail.com.br", "livemail.com.br"], ["livemail.tw", "livemail.tw"], ["messengeruser.com", "messengeruser.com"], ["msn.com", "msn.com"], ["passport.com", "passport.com"],
        ["sympatico.ca", "sympatico.ca"], ["tw.live.com", "tw.live.com"], ["webtv.net", "webtv.net"], ["windowslive.com", "windowslive.com"], ["windowslive.es", "windowslive.es"]
      ]
      "@" + select_tag("suffix", options_for_select(hotmail_suffix))
    end
  end
end

app/views/friends/_find_people_for.html.erb
<div class="col300 inboxMess" style="background:#ffffff;border: 1px solid #DBDBDB">
  <div class="col300in" style="background:#ffffff">
    <div class="searchPInput">
      <div class="searchFri" style="height:27px;width:226px">
        <%
        if logged_in?
          path = find_people_user_friends_url(current_user) 
        else
          path = "/friends/find_people_without_login"
        end 
      %>
        <form id="action_people_search" name="search" action="<%= path %>" method="get">
          <div class="textS" style="background-image: none;">
            <input id="search_people_txt" type="text" name="search[query]" value="Search for friends" class="focus_text_field" style="height: 14px;margin-top: 3px;width: 222px;padding-top: 2px;"/>
          </div>
          <div class="btmS" style="float: right;padding-left: 0px;padding-top: 4px">
            <a id="btnFrie_submit" href="javascript:;" onclick="$('#action_people_search').submit();">
              <img src="/images/AsD-iconS.png" style="width:24px;float: right;margin-right: -22px;margin-top: -24px;"/>
            </a>
          </div>
        </form>
        <div class="people_search" style="margin-left:34px">
          <%= render :partial => "friends/people_search" %>
        </div>
      </div>
    </div>
    <div class="sugges" style="float:left;">
      Suggestions
    </div>
    <div id="suggestion_list" class="suggesList" style="float:left;width:100%;">
      <div class="suggesRow">
        <%
        if current_user
          @suggestions = current_user.suggestions
        else
          @suggestions = User.order("RAND()").limit(10)
        end
      %>
        <% @suggestions.each do |u| %>
          <div class="suggesItem" style="width:140px;">
            <div class="AsDContImg">
              <%= show_image_user_post(u) %>
            </div>
            <div class="suggesName" style="padding-top:0px">
              <%= show_user_post(u) %>
            </div>
            <div class="suggesAdd">
              <span id="friend_status_<%= u.id %>"><%= show_invite_friend(u) %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="friConnect" style="clear: both;padding: 5px 10px;">        
    <div class="friConnect11 <%= "friSelect" if action_name == "invite" %>" style="border-top: 1px solid #E4E4E4;padding: 6px 0 6px 24px;background: url(/images/iconF11.png) no-repeat scroll left 4px transparent;">
      <%= link_to("Invite Your Facebook Friends", "#", :id => "invite_fb_friends") %>
    </div>  
  </div>
  <div id="friends">
    <div id="fb-root"></div>

    <script src="https://connect.facebook.net/en_US/all.js"></script>

    <script>
      $(function(){
    
        $("a#invite_fb_friends").click(function() {
          FB.init({ 
            appId:'<%= Facebook::APP_ID.to_s %>', 
            cookie:false, 
            status:true
          });
      
          FB.ui({ method: 'apprequests', message: 'I found AfterClassroom as a great place for socialize and study after school, thus I would like to invite you to join.'});
        });
      });
    </script>
  </div>
</div>

<script>
  var path_people = "/friends/find_people_suggestion";
  $().ready(function(){
    $('#search_people_txt').autocomplete({
      source: function(request, response) {
        $('#btnFrie_submit').append('<%= show_ajax_loader("loader_id_fri","display: block; position: absolute; float: right; height: 19px; margin-top: -21.5px; margin-left: -20px;") %>');
        $.ajax({
          type: 'GET',
          url: path_people,
          data: {search_name: $('#search_people_txt').val()},
          success: function(data) {
            $('#search_people_list').html(data);
            $('#search_people_wrap').show();
            $('#loader_id_fri').remove();
          }
        });
      }
    });
  });
  $(document).ready(function(){
    $('#action_people_search').css({
      'position':'absolute',
      'width':'226px'
    });
    $('.suggesName a').css({
      'word-wrap': 'break-word', 
      'width': '70px',
      'float':'left',
      'overflow':'hidden',
      'height': '15px'
    });
    $('.suggesItem .AsDContImg div').css({
      'height': '52px'
    });
    $('.flistRclose').click(function(){
      $('.asslinkdownSt_UserL').hide();
    });
  });
</script>

app/views/friends/_friend_search.html.erb
<div class="asslinkdownSt_UserRa" id="search_friend_wrap">
  <span class="flistRclosea">
    <a title="Close" class="vtip" id="flistRclosea"></a>
  </span>
  <div class="contMainL" style="width: 278px">
    <div class="col451s">
      <div class="col451ins">
        <div class="col451Cont">
          <div id="search_friend_lista" style="min-height: 50px">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friends/_item_friend_suggestion.html.erb
<div class="flistItem">
  <div class="assPic">
    <%= show_image_user_post(friend) %>
  </div>
  <div class="flistInf" style="width:195px">
    <div class="flistN">
      <%= show_user_post(friend) %>
    </div><br></br>
		<% if friend.school %>
    <div class="flistS">
      <span>at</span>
      <%= friend.school.name %>
    </div>
		<% end %>
  </div>
</div>

app/views/friends/_leftmenu.html.erb
<div class="col195 friLeft">
  <div class="col195in">
    <div class="search">
      <%= render :partial => "search_friend_form" %>
    </div>    
    <div class="friConnect">
      <div class="friConnect1 <%= "friSelect" if action_name == "index" %>"><%= link_to "All connection (#{@user.user_friends.length.to_s})", user_friends_path(current_user) %></div>
      <div class="friConnect2 <%= "friSelect" if action_name == "find" %>"><%= link_to "Find friends", find_user_friends_path(current_user) %></div>
      <div class="friConnect4 <%= "friSelect" if action_name == "recently_added" %>"><%= link_to "Recently Added (#{@count_recentadded.to_s})", recently_added_user_friends_path(current_user) %></div>
      <div class="friConnect5 <%= "friSelect" if action_name == "recently_updated" %>"><%= link_to "Recently Updated (#{@user.user_friends.length.to_s})", recently_updated_user_friends_path(current_user) %></div>
      <div class="friConnect11 <%= "friSelect" if action_name == "friend_request" %>"><%= link_to "Friend Requests (#{@count_request.to_s})", friend_request_user_friends_path(current_user) %></div>
    </div>
    <div class="friendL">List</div>
    <div class="friConnect">   
      <div class="friConnect6 <%= "friSelect" if action_name == "list" && @group == "family_members" %>"><%= link_to "Family members (#{@count_faminly.to_s})", list_user_friends_path(current_user, :group => "family_members") %></div>
      <div class="friConnect7 <%= "friSelect" if action_name == "list" && @group == "friends_from_school" %>"><%= link_to "Friends from school (#{@count_sch})", list_user_friends_path(current_user, :group => "friends_from_school") %></div>
      <div class="friConnect8 <%= "friSelect" if action_name == "list" && @group == "friends_from_work" %>"><%= link_to "Friends from work (#{@count_work.to_s})", list_user_friends_path(current_user, :group => "friends_from_work") %></div>
      <div class="friConnect11 <%= "friSelect" if action_name == "invite" %>"><%= link_to "Invite Friends to join AfterClassroom", invite_user_friends_path(current_user) %></div>
      <div class="friConnect11 <%= "friSelect" if action_name == "invite" %>">
        <%= link_to("Invite Your Facebook Friends", "#", :id => "invite_fb_friends") %>
      </div>
      <!--
<div class="friConnect11 <%= "friSelect" if action_name == "invite" %>">
      <%= link_to("Invite Your LinkedIn Friends", "/friends/auth_linkedin", :class => "newWindow") %>
</div>
			-->
    </div>
  </div>
</div>
<script>
  $(".friConnect6 a, .friConnect7 a, .friConnect8 a, .friConnect9 a").each(function() {
    if(this.href == window.location) $(this).addClass("active-page");
  });
</script>

<div id="friends">
  <div id="fb-root"></div>

  <script src="https://connect.facebook.net/en_US/all.js"></script>

  <script>
    $(function(){
    
      $("a#invite_fb_friends").click(function() {
        FB.init({ 
          appId:'<%= Facebook::APP_ID.to_s %>', 
          cookie:false, 
          status:true
        });
      
        FB.ui({ method: 'apprequests', message: 'I found AfterClassroom as a great place for socialize and study after school, thus I would like to invite you to join.'});
      });
    });
  </script>
</div>
<script>
  $(document).ready(function(){
    var windowSizeArray = [ "width=500,height=450", "width=500,height=450,scrollbars=no" ];
    $(document).ready(function(){
      $('.newWindow').click(function (event){
        var url = $(this).attr("href");
        var windowName = "popUp";//$(this).attr("name");
        var windowSize = windowSizeArray[$(this).attr("rel")];
        window.open(url, windowName, windowSize);
        event.preventDefault();
      });
    });
  });
  var path_friend = "<%= search_suggestion_user_friends_path(current_user) %>";
  $().ready(function(){   
    $('#search_friend_txt').autocomplete({ 
      source: function(request, response) {
        $('#btnFri_submit').append('<%= show_ajax_loader("loader_id_frie","display: block; position: absolute; float: right; height: 19px; margin-top: -19px; margin-left: -25px;") %>');
        $.ajax({
          type: 'GET',
          url: path_friend,
          data: {search_name: $('#search_friend_txt').val()},        
          success: function(data) {          
            $('#search_friend_lista').html(data);
            $('#search_friend_wrap').show();
            $('#loader_id_frie').remove();
          }
        });
      }
    });
  });
  $(document).ready(function(){
    vtip()
  });
  $(document).ready(function(){
    $('#flistRclosea').click(function(){
      $('.asslinkdownSt_UserRa').hide();
    });
  });
  $(document).ready(function(){
    $('.contMainR').hover(function(){
      $('.asslinkdownSt_UserRa').hide();
    })
    $('.contMainC').hover(function(){
      $('.asslinkdownSt_UserL').hide();
    })
  });
</script>

app/views/friends/_mail_form.html.erb
<%= form_for :mail_account, @mail_account, :url => find_email_user_friends_path(current_user), :html => {:id => "form_account_email"} do |f| %>
  <div class="error" style="padding: 10px; display:none;"></div>
  <div class="findItem">
    <div class="findText">Your Email*</div>
    <div class="findIn"><%= f.text_field :login, :style => "width:150px", :class => 'required true' %><span id="mail_type_span"><%= render :partial => "mail_type" %></span></div>
  </div>
  <div class="findItem">
    <div class="findText">Email Password*</div>
    <div class="findIn"><%= f.password_field :password, :style => "width:150px", :class => "required password" %></div>
  </div>
  <div class="btmFind"><a href="javascript:;" onclick="$('#form_account_email').submit();">Find Friends</a></div>
<% end %>
  
<script language="javascript">
  $(function () {
    $("#form_account_email").validate({
    });
  });
</script>

app/views/friends/_search_friend_form.html.erb
<%= form_tag search_user_friends_path(current_user), {:id => "friend_search", :method => "GET"} do %>
  <div class="textS"><%= text_field_tag "search[name]", "#{@search_name || "Search friends"}", :class => "focus_text_field", :id => "search_friend_txt" %></div>
  <div class="btmS"><a id="btnFri_submit" href="javascript:;" onclick="$('#friend_search').submit();"><img src="/images/iconSF.png"/></a></div>
    <% end %>
<span>
  <%= render :partial => "friend_search" %>
</span>
<script>
  var path_friend = "<%= search_suggestion_user_friends_path(current_user) %>";
  $().ready(function(){
    $('#search_friend_txt').autocomplete({
      source: function(request, response) {
        $('#btnFri_submit').append('<%= show_ajax_loader("loader_id_fr","display: block; position: absolute; float: right; height: 19px; margin-top: -19px; margin-left: -25px;") %>');
        $.ajax({
          type: 'GET',
          url: path_friend,
          data: {search_name: $('#search_friend_txt').val()},
          success: function(data) {
            $('#search_friend_lista').html(data);
            $('#search_friend_wrap').show();
            $('#loader_id_fr').hide();
          }
        });
      }
    });
  });
  $(document).ready(function(){
    $('#flistRclosea').click(function(){
      $('.asslinkdownSt_UserRa').hide();
    });
  });
</script>

app/views/friends/_submenu.html.erb
<div class="postdiv">
  <!--<span class="RmenuRbtm2"><a href="#">Post</a></span>-->
</div>

app/views/friends/accept.js.erb
$("#friend_request_<%= @invite_id %>").toggle();

if($('#friend_status_<%= @user_invite.id %>')){
	$('#friend_status_<%= @user_invite.id %>').html('<%= escape_javascript(link_to(raw("<span class='span1'><span class='span2'>Unfriend</span></span>"), unfriend_user_friends_url(current_user, :friend_id => @user_invite), :remote => true)) %>');
	$('#TB_closeWindowButton').click();
}

app/views/friends/de_accept.js.erb
$("#friend_request_<%= @invite_id %>").toggle();
if($('#friend_status_<%= @user_invite.id %>')){
	$('#friend_status_<%= @user_invite.id %>').html('<%= escape_javascript(link_to(raw("<span class='span1'><span class='span2' id='friend_#{@user_invite.id}'>Be friend</span></span>"), "#{show_invite_user_friends_path(current_user)}?user_invite=#{@user_invite.id}&height=300&width=470", :id => "link_invite", :class => "thickbox", :title => "Be friend with #{@user_invite.full_name}")) %>');
	$('#TB_closeWindowButton').click();
	//on page load call tb_init 
	tb_init(' div.menuRItem a.thickbox');//pass where to apply thickbox
}

app/views/friends/find_people.html.erb
<% content_for :menu_top_student_lounge do -%>
  <%= render :partial => 'submenu' %>
<% end -%>
<div class="contMainC">
  <%= render :partial => "leftmenu" %>
</div>
<div class="contMainL">
  <div class="col451 FriendSearch">
    <div class="col451in">
      <div class="col451Cont">
        <h1 class="titleH1">Search for People</h1>
        <div class="AsDsearch" style="margin-top:-37px">
          <form id="action_people_search" name="search" action="<%= find_people_user_friends_path(current_user) %>" method="get">
            <div class="AsDST">
              <input type="text" name="search[query]" value="<%= @query || "Enter your search keywords..." %>" onblur="this.value = this.value || this.defaultValue;" onfocus="this.value = '';"/>
            </div>
            <div class="AsDSB">
              <a href="javascript:;" onclick="$('#action_people_search').submit();"><img src="/images/AsD-iconS.png"></a>
            </div>
          </form>
        </div>
        <div id="friend_list">
          <%= display_flash_messages_with_raw %>
          <% @users.each_hit_with_result do |hit, u| %>
            <%= render :partial => "item_people", :locals => {:user => u, :name => raw(hit.highlight(:name) ? hit.highlight(:name).format { |fragment| content_tag(:em, fragment) } : u.name) } %>
          <% end %>
          <!--Pagination-->
          <div class="assPage">
            <span class="numPage"><%= page_entries_info @users.results %></span>
            <%= will_paginate @users.results %>
          </div>
          <!--Pagination-->
        </div>
      </div>
    </div>
  </div>
</div>
<div class="contMainR">
  <!--Find people-->
  <%= render :partial => "find_people" %>
  <!--Find people-->
  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->
</div>

app/views/friends/unfriend.js.erb
$("#friend_status_<%= @user.id %>").html("<%= escape_javascript(link_to(raw("<span class='span1'><span class='span2' id='friend_#{@user.id}'>Be friend</span></span>"), "#{show_invite_user_friends_path(current_user)}?user_invite=#{@user.id}&height=300&width=470", :id => "link_invite", :class => "thickbox", :title => "Be friend with #{@user.full_name}")) %>"); 
//on page load call tb_init 
tb_init('#friend_status_<%= @user.id %> a.thickbox');//pass where to apply thickbox