config/routes.rb
Afterclassroom::Application.routes.draw do
  resources :omnitauths

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  # RESTful rewrites
	match '/login' => 'sessions#new', :as => :login
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/logout' => 'sessions#destroy', :as => :logout, :conditions => {:method => :delete}

  match '/users/troubleshooting' => 'users#troubleshooting', :as => :user_troubleshooting
  match '/users/forgot_password' => 'users#forgot_password', :as => :user_forgot_password
  match '/users/reset_password/:password_reset_code' => 'users#reset_password', :as => :user_reset_password
  match '/users/forgot_login' => 'users#forgot_login', :as => :user_forgot_login
  match '/users/clueless' => 'users#clueless', :as => :user_clueless
  
  # Users
  resources :users do
    member do
      get :edit_password, :edit_email, :show_lounge, :show_stories, :show_story_detail, :show_photos, :show_photos_with_list, :show_photo_album, :show_photo_detail, :show_musics, :show_music_album, :show_videos, :show_detail_video, :show_friends, :show_fans, :warning, :warning_media,
        :list_friend_to_tag
      put :update_password, :update_email
      post :update_avatar, :remove_tagged, :add_tag, :tag_decision
    end
	
    #Messages
    resources :messages do
      collection do
        get :show_email, :list_friend, :delete_message
        post :message_action, :send_message
      end
    end
   
    #Learning tools
    resources :learn_tools do
      collection do
        get :index, :featured_tool_paging, :maylike_tool_paging, 
          :first_tab_paging, :search_tool, :see_all_tool_fan, :contact_dev_form, 
          :mylearn, :tool_rev_paging, :write_review_form, :become_a_fan,
          :new_tool, :verify_handler, :owner_handler, :video_list, :video_list_paging,
          :rate, :new_tool_with_api, :choose_to_add, :edit_review_form, :delete_review,
          :play_vid, :toolmanager, :edit_tool, :delete_tool, :fan_list_paging, :view_review,
          :add_mytool, :delete_fans
        post :submit_review, :submit_new_tool, :create_tool_with_api, 
          :send_to_dev,:update_review, :save_edit_tool
      end
    end    
    
    #Settings
    resources :settings do
      collection do
        get :networks, :notifications, :language,
          :payments, :ads, :setting, :private,
          :change_psw, :save_psw, :change_name,
          :save_name, :change_user_name, :save_user_name,
					:change_email, :save_email,
          :change_time_zone, :save_time_zone, :blocks, :unblock,
					:change_school, :save_school,
					:change_chat_id, :change_chat_yahoo_id, :save_chat_id
        post :save_setting, :save_private_setting, :check_login
      end
    end
 
    #Profiles
    resources :profiles do
      collection do
        get :show_profile, :edit_infor, :edit_edu_infor,
          :edit_work_infor, :my_favorite, :fan, :delete_fans, :delete_prof
        post :update_about_yourself, :update_infor, :update_edu_infor, :update_work_infor
      end
    end
    
    #Student lounges
    resources :student_lounges do
      collection do
        get :chat, :invite_chat, :add_users_to_chat, :stop_chat, :chanel_chat_content,
          :friends_changed_message, :friends_you_invited_chat, :friends_want_you_chat, :friends_online
        post :send_data
      end
    end

    #Friends
    resources :friends do
      collection do
        get :search, :search_suggestion, :find, :find_people, :recently_added, :recently_updated,
          :friend_request, :list, :invite, :unfriend, :display_email, :add_to_group,
          :send_invite_message, :show_invite, :become_a_fan, :accept, :de_accept, :respond_to_friend_request, :get_suggestion_list
        post :find_email, :invite_by_list_email,
          :invite_by_import_email, :delete, :show_list_email_contacts,
					:find_friend_by_email
      end
    end
	
    #Stories
    resources :stories do
      collection do
        get :friend_s, :my_s, :my_draft, :draft, :create_comment, :delete_comment, :delete_all, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    # Music Album
    resources :music_albums do
      collection do
        get :delete_all, :delete_musics, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :musics do
      collection do
        get :friend_m, :my_m, :create_playlist, :create_form, :play_list
        post :create_album, :upload
      end
    end

    # Photo Album
    resources :photo_albums do
      collection do
        get :delete_all, :delete_photos
      end
    end
    
    # Videos
    resources :videos do
      collection do
        get :friend_p, :my_p, :create_form, :delete_videos, :update_video, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :photos do
      collection do
        get :friend_p, :my_p, :create_form, :destroy_all, :show_album, :show_album_with_list, :phototag, :deletetag, :addtag, :usrdata, :self_untag
        post :create_album, :upload, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    resources :u_forums do
      collection do
        get :dft_stgs, :post_lounge, :item_setting, :post_lounge_b, :rate, :friend_pad, :find_people, 
        :select_share, :page_share, :add_usr, :remove_usr, :page_member, :add_usr_show, :page_share_show, :remove_usr_show, 
        :friend_pad_show, :find_people_show, :unsubscribe, :del_cmt, :subscribe
        post :save_setting, :save_custom, :save_cmt, :save_custom_b, :remove_member, :add_more_member
      end
      
    end

    # Youtube
    resources :youtubes do
      new do
        post :upload
      end

      collection do
        get :authorise
      end
    end
  
    # Post managements
    resources :post_managements do
      collection do
        get :with_type, :delete_all
      end
    end
    
    # Share files
    resources :shares
  end

  # Sessions
  resource :session do
    collection do
      get :change_school
    end
  end

  # State
  resources :states

  # City
  resources :cities do 
    collection do
      get :state
    end
  end

  #Rate comment 
  resources :rate_cmts do
    collection do
      get :load_bk_like, :load_bk_dislike, :load_other
      post :add_like_cmt, :add_like_cmt
    end
  end    


  # School
  resources :schools do
    collection do
      get :state_or_city, :city
    end
  end

  # Posts
  resources :posts do
    collection do
      get :report_abuse, :create_report_abuse, :report_abuse_video, :create_report_abuse_video, :delete_comment, :download, :view_all_comments, :report_abuse_vid, :comments_list, :remove_attach_file
      post :create_comment_on_list, :create_comment
    end
  end

  resources :post_assignments do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_projects do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_tests do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end
  
  resources :post_exams do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_events do
    collection do
      get :search, :tag, :rate
    end
  end

  resources :post_qas do
    collection do
      get :search, :tag, :interesting, :top_answer, :create_comment, :rate, :require_rate, :prefer, :sendmail
    end
  end

  resources :post_tutors do
    collection do
      get :search, :tag, :effective, :dont_hire, :rate, :require_rate
    end
  end

  resources :post_books do
    collection do
      get :search, :tag, :good_books, :dont_buy, :rate, :require_rate
    end
  end

  resources :post_jobs do
    collection do
      get :search, :tag, :good_companies, :bad_bosses,
        :rate, :require_rate, :my_job_list, :add_job,
        :employment_infor, :show_job_infor, :apply_job,
        :save_letter, :save_script, :save_resume, :delete_job_list
    end
  end

  resources :post_foods do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_parties do
    collection do
      get :search, :show_rsvp, :create_rsvp,
        :tag, :rate, :require_rate,
        :prefer, :my_party_list, :add_party, :delete_party_list, :sendmail
    end
  end

  resources :post_myxes do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_awarenesses do
    collection do
      get :search, :tag, :rate, :support, :require_rate
    end
  end

  resources :post_housings do
    collection do
      get :search, :tag, :good_house, :worse_house, :rate
    end
  end

  resources :post_teamups do
    collection do
      get :search, :tag, :good_org, :worse_org, :more_startup, :rate
    end
  end

  # Exam/Test Schedules, Deadline bulletin, General bulletin
  resources :post_exam_schedules do
    collection do
      get :search, :tag, :rate
    end
  end
  
    resources :post_lecture_notes do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end
  
  #Ajax not login
  resources :ajax_not_login do
    collection do
      get :show_comment, :rate_comment, :rate_comment_action, :view_results, :view_press_info_detail, :view_career_detail
    end
  end
  
  # Feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  # Tags
  resources :tags do
    collection do
      get :show_tags, :show_tags_list
    end
  end
  
  #Simple Captcha
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  
  #Forums
  resources :forums do 
    collection do

app/controllers/post_teamups_controller.rb
# -*- coding: utf-8 -*-
# © Copyright 2009 AfterClassroom.com — All Rights Reserved
class PostTeamupsController < ApplicationController
  #before_filter RubyCAS::Filter::GatewayFilter
  #before_filter RubyCAS::Filter, :except => [:index, :show, :search, :tag, :good_org, :worse_org]
  #before_filter :cas_user
	before_filter :login_required, :except => [:index, :show, :search, :tag, :good_org, :worse_org]
  before_filter :get_variables, :only => [:index, :show, :new, :create, :edit, :update, :search, :tag, :good_org, :worse_org]
  before_filter :require_current_user, :only => [:edit, :update, :destroy]
  after_filter :store_location, :only => [:index, :show, :new, :edit, :search, :tag, :good_org, :worse_org]
  cache_sweeper :post_sweeper, :only => [:create, :update, :detroy]
  
  # GET /post_teamups
  # GET /post_teamups.xml
  def index
    @teamup_category_id = params[:teamup_category_id]
    @teamup_category_id ||= TeamupCategory.find(:first).id
    @post_results = Rails.cache.fetch("index_#{@class_name}_category#{@teamup_category_id}_#{@school}_year#{params[:year]}_department#{params[:department]}_over#{params[:over]}") do
      PostTeamup.paginated_post_conditions_with_option(params, @school, @teamup_category_id)
    end
    @posts = @post_results.paginate({:page => params[:page], :per_page => 10})
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  def search
    @query = params[:search][:query] if params[:search]
    if params[:search]
      @posts = Post.paginated_post_conditions_with_search(params, @school, @type)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  def tag
    @tag_name = params[:tag_name]
    @posts = PostTeamup.paginated_post_conditions_with_tag(params, @school, @tag_name)
  end
  
  def good_org
    @posts = PostTeamup.paginated_post_conditions_with_good_org(params, @school)
  end
  
  def worse_org
    @posts = PostTeamup.paginated_post_conditions_with_worse_org(params, @school)
  end
  
  def rate
    rating = params[:rating]
    @post = Post.find(params[:post_id])
    @post_tm = @post.post_teamup
    @post_tm.rate rating.to_i, current_user
    # Update rating status
    score_good = @post_tm.score_good
    score_bad = @post_tm.score_bad
    
    if score_good > score_bad
      status = "Good"
    elsif score_good == score_bad
      status = "Require Rating"
    else
      status = "Bad"
    end
    
    @post_tm.rating_status = status
    @post_tm.save

    # support for rate like/dislike cmt
    @str_class = "PostTeamup"

  end
  
  # GET /post_teamups/1
  # GET /post_teamups/1.xml
  def show
    @post_teamup = PostTeamup.find(params[:id])
    @post = @post_teamup.post
    @teamup_category_id = @post_teamup.teamup_category_id
    update_view_count(@post)
    posts_as = PostTeamup.with_school(@school).with_category(@teamup_category_id)
    as_next = posts_as.nexts(@post_teamup.id).last
    as_prev = posts_as.previous(@post_teamup.id).first
    @next = as_next if as_next
    @prev = as_prev if as_prev
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post_teamup }
    end
  end
  
  # GET /post_teamups/new
  # GET /post_teamups/new.xml
  def new
    @post_teamup = PostTeamup.new
    @post = Post.new
    @post_teamup.post = @post
    @post_teamup.teamup_category_id = TeamupCategory.first.id
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post_teamup }
    end
  end
  
  # GET /post_teamups/1/edit
  def edit
    @post_teamup = PostTeamup.find(params[:id])
    @post = @post_teamup.post
    @tag_list = @post_teamup.tags_from(@post.school).join(", ")
  end
  
  # POST /post_teamups
  # POST /post_teamups.xml
  def create
    @tag_list = params[:tag]
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.school_id = @school
    @post.post_category_id = @type
    @post.type_name = @class_name
    @post_teamup = PostTeamup.new(params[:post_teamup])
    @post_teamup.teamup_category_id ||= TeamupCategory.first.id
    if @school.nil?
			flash[:error] = "Please select school."
		  render :action => "new"
		else
		  if simple_captcha_valid?   
		    @post.save     
		    sc = School.find(@school)
		    sc.tag(@post_teamup, :with => @tag_list, :on => :tags)
		    @post_teamup.post = @post
		    
		    if @post_teamup.save
		      flash[:notice] = "Your post was successfully created."
		      post_wall(@post_teamup)
		      redirect_to post_teamup_path(@post_teamup)
		    else
		      flash[:error] = "Failed to create a new post."
		      render :action => "new"
		    end
		  else
		    flash[:warning] = "Captcha does not match."
		    render :action => "new"
		  end
		end
  end
  
  # PUT /post_teamups/1
  # PUT /post_teamups/1.xml
  def update
    @post_teamup = PostTeamup.find(params[:id])
    @post = @post_teamup.post
    
    if (@post_teamup.update_attributes(params[:post_teamup]) && @post_teamup.post.update_attributes(params[:post]))
      sc = School.find(@post.school.id)
      sc.tag(@post_teamup, :with => params[:tag], :on => :tags)
      redirect_to post_teamup_path(@post_teamup)
    end
  end
  
  # DELETE /post_teamups/1
  # DELETE /post_teamups/1.xml
  def destroy
    @post_teamup = PostTeamup.find(params[:id])
    @post_teamup.post.favorites.destroy_all
    del_post_wall(@post_teamup)
    @post_teamup.destroy
    
    redirect_to my_post_user_url(current_user)
  end
  
  private
  
  def get_variables
    @school = session[:your_school]
    @new_post_path = new_post_teamup_path
    @class_name = "PostTeamup"
    @type = PostCategory.find_by_class_name(@class_name).id
    @query = params[:search][:query] if params[:search]
    @departments = Department.of_school(@school)
    if !fragment_exist? :browser_by_subject
      if @school
        @tags = School.find(@school).owned_tags.where(["taggable_type = ?", @class_name])
      else
        @tags = eval(@class_name).tag_counts
      end
    end
  end
  
  def require_current_user
    post_teamup = PostTeamup.find(params[:id])
    post = post_teamup.post
    @user ||= post.user
    unless (@user && (@user.eql?(current_user))) || current_user.has_role?(:admin)
      redirect_back_or_default(root_path)and return false
    end
    return @user
  end
end

app/views/post_teamups/_good_org.html.erb
<div class="col195 student195">
  <div class="col195in">
    <h1 class="col195Title">Good organizations</h1>
    <div class="col195Cont">
      <%
      good_org = PostTeamup.with_limit.good_org(@school)
    %>
      <% if good_org.size > 0 %>
        <%
        good_org.each do |tt|
        %>
          <div class="studentItem">
            <div class="studentImg"><%= show_image_user_post(tt.post.user) %></div>
            <div class="studentInf"><%= link_to truncate_words(tt.post.title, 4), post_teamup_path(tt) %></div>
          </div>
        <% end %>
		<% if good_org.size > LIMIT - 1 %>
        <div class="dueDbutton"><%= link_to "View more Good organizations", good_org_post_teamups_path %></div>
		<% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/post_teamups/_startup.html.erb
<div class="col195 student195">
    <div class="col195in">
        <h1 class="col195Title">TeamUp for Start-up</h1>
        <div class="col195Cont">
            <%
            team_s = TeamupCategory.find_by_label("teamup_for_start_up")
            team_startups = PostTeamup.with_school(@school).with_category(team_s.id).recent.with_limit %>
            <% if team_startups.size > 0 %>
            <%
            team_startups.each do |ts| %>
            <div class="studentItem">
                <div class="studentImg">
                    <%= show_image_user_post(ts.post.user) %>
                </div>
                <div class="studentInf">
                    <%= link_to truncate_words(ts.post.title, 4), post_teamup_path(ts) %>
                </div>
            </div>
            <%
            end
            end %>
        </div>
				<% if team_startups.size > LIMIT - 1 %>
        <div class="dueDbutton">
            <a href="<%= "#{post_teamups_path}?teamup_category_id=#{team_s.id}"  %>">View more Teamup for Start-up</a>
        </div>
				<% end %>
    </div>
</div>

app/views/post_teamups/_submenu.html.erb
<% TeamupCategory.find(:all).each do |tt| %>
<div class="menuRItem <%= "menuRselect" if @teamup_category_id && @teamup_category_id.to_i == tt.id %>"><a href="<%= "#{post_teamups_path}?teamup_category_id=#{tt.id}" %>"><span class="span1"><span class="span2"><%= tt.name %></span></span></a></div>
<% end %>

<% if logged_in? %>
<div style="margin-left:20px" class="menuRItem">
    <a href="<%= "#{user_post_managements_url(current_user)}?category=#{@class_name}"  %>"><span class="span1"><span class="span2">Post management</span></span></a>
</div>
<% end %>

app/views/post_teamups/_worse_org.html.erb
<div class="col195 student195">
  <div class="col195in">
    <h1 class="col195Title">Worse organizations</h1>
    <div class="col195Cont">
      <%
      worse_org = PostTeamup.with_limit.worse_org(@school)
    %>
      <% if worse_org.size > 0 %>
        <%
        worse_org.each do |tt|
        %>
          <div class="studentItem">
            <div class="studentImg"><%= show_image_user_post(tt.post.user) %></div>
            <div class="studentInf"><%= link_to truncate_words(tt.post.title, 4), post_teamup_path(tt) %></div>
          </div>
        <% end %>
		<% if worse_org.size > LIMIT - 1 %>
        <div class="dueDbutton"><%= link_to "View more Worse organizations", worse_org_post_teamups_path %></div>
		<% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/post_teamups/edit.html.erb
<% content_for :you_are_here do -%>
  You are here: <a href="/">Home</a><%= link_to "TeamUp", post_teamups_path, :class => "abLink-detail" %><%= link_to "Edit", "#", :class => "abLink-detail" %>
<% end -%>

<% content_for :post_button do -%>
  <%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>

<% content_for :menu_sub do -%>
  <%= render :partial => "submenu" %>
<% end -%>

<!--Content-->
<div class="contDetL">
  <div class="contDetLin post">
    <div class="AsDTop">
      <h1 class="titleH1">Posting to the world!</h1>
    </div>
    <div class="postCont">
    	<%= display_flash_messages_with_raw %>
      <%= form_for(@post_teamup, :html => {:multipart => true, :id => "form_post" }) do |f| %>
        <%= render :partial => "form", :locals => {:f => f} %>
        <div class="submit"><a href="javascript:;" id="submit_form">Send</a></div>
      <% end %>
    </div>
  </div>
</div>

<div class="contMainR">
  <!--Browser by Subject-->
  <%= render :partial => "shared/browser_by_subject" %>
  <!--Browser by Subject-->

  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->
</div>
<!--Content-->
<script>
  $(document).ready(function(){
    $('#submit_form').click(function(){
      submitForm();
    });
  });
</script>

app/views/post_teamups/rate.js.erb
$("#rate_<%= @post.id %>_<%= @post.class.name %>").html("<div class='qashdU'><a href='javascript:;' class='vtip' title='<%= configatron.str_rated %>'><%= @post_tm.total_good %></a></div><div class='qashdD'><a href='javascript:;' class='vtip' title='<%= configatron.str_rated %>'><%= @post_tm.total_bad %></a></div><script>vtip();</script>'");
<%= render :partial => "rate_cmts/cmt_script_b" %>

app/views/post_teamups/search.html.erb
<% content_for :you_are_here do -%>
  You are here: <a href="/">Home</a><%= link_to "Team Up", post_teamups_path, :class => "abLink-detail" %><%= link_to "Search", "#", :class => "abLink-detail" %>
<% end -%>

<% content_for :post_button do -%>
  <%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>

<% content_for :menu_sub do -%>
  <%= render :partial => "submenu" %>
<% end -%>

<!--Content-->
<div class="contMainL">
  <div class="col451 student">
    <div class="col451in">
      <div class="col451Cont">
        <div class="AsDTop">
          <h1 class="titleH1">Team Up</h1>
          <div class="AsDsearch">
            <%= render :partial => "shared/search_indetail", :locals => {:url_search => search_post_teamups_path} %>
          </div>
        </div>
		<%= display_flash_messages_with_raw %>
        <!--List Items-->
        <% @posts.each_hit_with_result do |hit, post| %>
          <div id="post_<%= post.id %>"><%= render :partial => "item", :locals => {:post => post, :title => post.title, :description => raw(hit.highlight(:description) ? hit.highlight(:description).format { |fragment| content_tag(:em, fragment) } : post.description), :controller_name => controller.controller_name} %></div>
        <% end %>
        <!--List Items-->

        <!--Pagination-->
        <div class="assPage">
          <span class="numPage"><%= page_entries_info @posts.results %></span>
          <%= will_paginate @posts.results %>
        </div>
        <!--Pagination-->
        <div class="goTop"><a href="javascript:;" onclick="goToByScroll('top_page')">Top</a></div>
      </div>
    </div>
  </div>
</div>

<div class="contMainC">
  <!--Browser Startup-->
  <%= render :partial => "startup"%>
  <!--Browser Startup-->

  <!--Browser Good organizations-->
  <%= render :partial => "good_org"%>
  <!--Browser Good organizations-->

  <!--Browser Bad organizations-->
  <%= render :partial => "worse_org"%>
  <!--Browser Bad organizations-->
</div>

<div class="contMainR">
  <!--Browser by Subject-->
  <%= render :partial => "shared/browser_by_subject" %>
  <!--Browser by Subject-->

  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->

  <!--Request teamup-->
  <%= render :partial => "form_request_teamup" %>
  <!--Request teamup-->
  
  <!--Recent Request Comments-->
  <%= render :partial => "recent_comments" %>
  <!--Recent Request Comments-->

</div>
<!--Content-->

app/views/post_teamups/show.html.erb
<% content_for :you_are_here do -%>
You are here: <a href="/">Home</a>
<%= link_to "Team Up", post_teamups_path(:teamup_category_id => @teamup_category_id), :class => "abLink-detail" %><%= link_to "Detail", "#", :class => "abLink-detail" %>
<% end -%>
<% content_for :post_button do -%>
<%= render :partial => 'shared/post_button', :locals => {:new_post_path => @new_post_path} %>
<% end -%>
<% content_for :menu_sub do -%>
<%= render :partial => "submenu" %>
<% end -%>
<!--Content-->
<div class="contDetL">
    <div class="contDetLin">
        <div class="AsDTop">
            <h1 class="titleH1">Team Up detail</h1>
            <div class="AsDsearch">
                <%= render :partial => "shared/search_indetail", :locals => {:url_search => search_post_teamups_path} %>
            </div>
        </div>
        <div class="AsDCont">
            <%= display_flash_messages_with_raw %>
            <div class="AsDContL">
                <h2 class="titleH2"><%= @post.title %></h2>
                <div class="AsDContLdes">
                    <span>Description:</span>
                    <% if @post.attach_file_name and @post.attach_content_type =~ /^image.*/ %>
                    <div style="min-height:70px">
                        <div class="assImg">
                            <div>
                                <%= link_to image_tag(@post.attach.url(:thumb)), @post.attach.url, :class => "imageLink", :target => "_blank" %>
                            </div>
                        </div>
                        <%= @post.description %>
                    </div>
                    <% else %>
                    <%= @post.description %>
                    <% end %>
                </div>
                <div class="AsDContLinf">
                    <span>Posted by:</span>
                    <%= show_user_post(@post.user) %> - <%= time_ago_in_words(@post.created_at, true) + " ago." %>
                </div>
                <% if @post_teamup.tags_from(@post.school).size > 0 %>
                <div class="AsDContLinf">
                    <span>Tags:</span>
                    <% @post_teamup.tags_from(@post.school).each do |t| %>
                    <a href='/<%= controller.controller_name %>/tag/?tag_name=<%= t %>'><%= t %></a>, <% end %>
                </div>
                <% end %>
            </div>
            <%= render :partial => "shared/user_infor", :locals => {:user => @post.user, :post => @post} %>
            <%= render :partial => "post_actions", :locals => {:post => @post} %>
        </div>
        <%= show_post_comments(@post) %>
        <div class="goback" id="go_back">
            <%= show_go_back %>
        </div>
        <div class="comPage">
            <span></span>
            <span class="compre"><%= link_to "", post_teamup_path(@prev) if @prev %></span>
            <span class="comnext"><%= link_to "", post_teamup_path(@next) if @next %></span>
        </div>
        <div class="AsDOr">
            <h1 class="titleH1">Related posts</h1>
            <% PostTeamup.related_posts(@school, @teamup_category_id).each do |p| %>
            <div class="AsDOrItem">
                <%= link_to p.title, post_teamup_path(p.post_teamup) %>
            </div>
            <% end %>
        </div>
        <div class="goTop">
            <a href="javascript:;" onclick="goToByScroll('top_page')">Top</a>
        </div>
    </div>
</div>
<div class="contMainR">
    <!--Ads-->
    <%= render :partial => "ads/show_vertical_ads" %>
    <!--Ads-->
    <!--Recent Request Comments-->
    <%= render :partial => "recent_comments" %>
    <!--Recent Request Comments--
    <!--Recent Actives-->
    <%#= render :partial => "shared/recent_active" %>
    <!--Recent Actives-->
</div>
<!--Content-->