config/routes.rb
Afterclassroom::Application.routes.draw do
  resources :omnitauths

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  # RESTful rewrites
	match '/login' => 'sessions#new', :as => :login
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/logout' => 'sessions#destroy', :as => :logout, :conditions => {:method => :delete}

  match '/users/troubleshooting' => 'users#troubleshooting', :as => :user_troubleshooting
  match '/users/forgot_password' => 'users#forgot_password', :as => :user_forgot_password
  match '/users/reset_password/:password_reset_code' => 'users#reset_password', :as => :user_reset_password
  match '/users/forgot_login' => 'users#forgot_login', :as => :user_forgot_login
  match '/users/clueless' => 'users#clueless', :as => :user_clueless
  
  # Users
  resources :users do
    member do
      get :edit_password, :edit_email, :show_lounge, :show_stories, :show_story_detail, :show_photos, :show_photos_with_list, :show_photo_album, :show_photo_detail, :show_musics, :show_music_album, :show_videos, :show_detail_video, :show_friends, :show_fans, :warning, :warning_media,
        :list_friend_to_tag
      put :update_password, :update_email
      post :update_avatar, :remove_tagged, :add_tag, :tag_decision
    end
	
    #Messages
    resources :messages do
      collection do
        get :show_email, :list_friend, :delete_message
        post :message_action, :send_message
      end
    end
   
    #Learning tools
    resources :learn_tools do
      collection do
        get :index, :featured_tool_paging, :maylike_tool_paging, 
          :first_tab_paging, :search_tool, :see_all_tool_fan, :contact_dev_form, 
          :mylearn, :tool_rev_paging, :write_review_form, :become_a_fan,
          :new_tool, :verify_handler, :owner_handler, :video_list, :video_list_paging,
          :rate, :new_tool_with_api, :choose_to_add, :edit_review_form, :delete_review,
          :play_vid, :toolmanager, :edit_tool, :delete_tool, :fan_list_paging, :view_review,
          :add_mytool, :delete_fans
        post :submit_review, :submit_new_tool, :create_tool_with_api, 
          :send_to_dev,:update_review, :save_edit_tool
      end
    end    
    
    #Settings
    resources :settings do
      collection do
        get :networks, :notifications, :language,
          :payments, :ads, :setting, :private,
          :change_psw, :save_psw, :change_name,
          :save_name, :change_user_name, :save_user_name,
					:change_email, :save_email,
          :change_time_zone, :save_time_zone, :blocks, :unblock,
					:change_school, :save_school,
					:change_chat_id, :change_chat_yahoo_id, :save_chat_id
        post :save_setting, :save_private_setting, :check_login
      end
    end
 
    #Profiles
    resources :profiles do
      collection do
        get :show_profile, :edit_infor, :edit_edu_infor,
          :edit_work_infor, :my_favorite, :fan, :delete_fans, :delete_prof
        post :update_about_yourself, :update_infor, :update_edu_infor, :update_work_infor
      end
    end
    
    #Student lounges
    resources :student_lounges do
      collection do
        get :chat, :invite_chat, :add_users_to_chat, :stop_chat, :chanel_chat_content,
          :friends_changed_message, :friends_you_invited_chat, :friends_want_you_chat, :friends_online
        post :send_data
      end
    end

    #Friends
    resources :friends do
      collection do
        get :search, :search_suggestion, :find, :find_people, :recently_added, :recently_updated,
          :friend_request, :list, :invite, :unfriend, :display_email, :add_to_group,
          :send_invite_message, :show_invite, :become_a_fan, :accept, :de_accept, :respond_to_friend_request, :get_suggestion_list
        post :find_email, :invite_by_list_email,
          :invite_by_import_email, :delete, :show_list_email_contacts,
					:find_friend_by_email
      end
    end
	
    #Stories
    resources :stories do
      collection do
        get :friend_s, :my_s, :my_draft, :draft, :create_comment, :delete_comment, :delete_all, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    # Music Album
    resources :music_albums do
      collection do
        get :delete_all, :delete_musics, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :musics do
      collection do
        get :friend_m, :my_m, :create_playlist, :create_form, :play_list
        post :create_album, :upload
      end
    end

    # Photo Album
    resources :photo_albums do
      collection do
        get :delete_all, :delete_photos
      end
    end
    
    # Videos
    resources :videos do
      collection do
        get :friend_p, :my_p, :create_form, :delete_videos, :update_video, :self_untag
        post :add_tag, :tag_decision, :remove_tagged, :comment_inform
      end
    end
    
    resources :photos do
      collection do
        get :friend_p, :my_p, :create_form, :destroy_all, :show_album, :show_album_with_list, :phototag, :deletetag, :addtag, :usrdata, :self_untag
        post :create_album, :upload, :tag_decision, :remove_tagged, :comment_inform
      end
    end

    resources :u_forums do
      collection do
        get :dft_stgs, :post_lounge, :item_setting, :post_lounge_b, :rate, :friend_pad, :find_people, 
        :select_share, :page_share, :add_usr, :remove_usr, :page_member, :add_usr_show, :page_share_show, :remove_usr_show, 
        :friend_pad_show, :find_people_show, :unsubscribe, :del_cmt, :subscribe
        post :save_setting, :save_custom, :save_cmt, :save_custom_b, :remove_member, :add_more_member
      end
      
    end

    # Youtube
    resources :youtubes do
      new do
        post :upload
      end

      collection do
        get :authorise
      end
    end
  
    # Post managements
    resources :post_managements do
      collection do
        get :with_type, :delete_all
      end
    end
    
    # Share files
    resources :shares
  end

  # Sessions
  resource :session do
    collection do
      get :change_school
    end
  end

  # State
  resources :states

  # City
  resources :cities do 
    collection do
      get :state
    end
  end

  #Rate comment 
  resources :rate_cmts do
    collection do
      get :load_bk_like, :load_bk_dislike, :load_other
      post :add_like_cmt, :add_like_cmt
    end
  end    


  # School
  resources :schools do
    collection do
      get :state_or_city, :city
    end
  end

  # Posts
  resources :posts do
    collection do
      get :report_abuse, :create_report_abuse, :report_abuse_video, :create_report_abuse_video, :delete_comment, :download, :view_all_comments, :report_abuse_vid, :comments_list, :remove_attach_file
      post :create_comment_on_list, :create_comment
    end
  end

  resources :post_assignments do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_projects do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_tests do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end
  
  resources :post_exams do
    collection do
      get :search, :interesting, :tag, :quick_post_form
    end
  end

  resources :post_events do
    collection do
      get :search, :tag, :rate
    end
  end

  resources :post_qas do
    collection do
      get :search, :tag, :interesting, :top_answer, :create_comment, :rate, :require_rate, :prefer, :sendmail
    end
  end

  resources :post_tutors do
    collection do
      get :search, :tag, :effective, :dont_hire, :rate, :require_rate
    end
  end

  resources :post_books do
    collection do
      get :search, :tag, :good_books, :dont_buy, :rate, :require_rate
    end
  end

  resources :post_jobs do
    collection do
      get :search, :tag, :good_companies, :bad_bosses,
        :rate, :require_rate, :my_job_list, :add_job,
        :employment_infor, :show_job_infor, :apply_job,
        :save_letter, :save_script, :save_resume, :delete_job_list
    end
  end

  resources :post_foods do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_parties do
    collection do
      get :search, :show_rsvp, :create_rsvp,
        :tag, :rate, :require_rate,
        :prefer, :my_party_list, :add_party, :delete_party_list, :sendmail
    end
  end

  resources :post_myxes do
    collection do
      get :search, :tag, :rate, :require_rate
    end
  end

  resources :post_awarenesses do
    collection do
      get :search, :tag, :rate, :support, :require_rate
    end
  end

  resources :post_housings do
    collection do
      get :search, :tag, :good_house, :worse_house, :rate
    end
  end

  resources :post_teamups do
    collection do
      get :search, :tag, :good_org, :worse_org, :more_startup, :rate
    end
  end

  # Exam/Test Schedules, Deadline bulletin, General bulletin
  resources :post_exam_schedules do
    collection do
      get :search, :tag, :rate
    end
  end
  
    resources :post_lecture_notes do
    collection do
      get :search, :due_date, :interesting, :tag, :quick_post_form
    end
  end
  
  #Ajax not login
  resources :ajax_not_login do
    collection do
      get :show_comment, :rate_comment, :rate_comment_action, :view_results, :view_press_info_detail, :view_career_detail
    end
  end
  
  # Feedback
  match 'feedbacks' => 'feedbacks#create', :as => :feedback
  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  # Tags
  resources :tags do
    collection do
      get :show_tags, :show_tags_list
    end
  end
  
  #Simple Captcha
  match 'simple_captcha/:id', :to => 'simple_captcha#show', :as => :simple_captcha
  
  #Forums
  resources :forums do 
    collection do

app/models/music.rb
# encoding: UTF-8
# © Copyright 2009 AfterClassroom.com — All Rights Reserved
require 'mime/types'
class Music < ActiveRecord::Base
	before_create :change_file_name
  # Relations
  belongs_to :user
  belongs_to :music_album
  
  # Attach
  has_attached_file :music_attach, {
    :bucket => 'afterclassroom_musics'
  }.merge(PAPERCLIP_STORAGE_OPTIONS)
  
  validates_attachment_presence :music_attach
  
  validates_attachment_size :music_attach, :less_than => FILE_SIZE_MUSIC
  
  validates_attachment_content_type :music_attach, :content_type => ['audio/mp3', 'audio/wav', 'audio/mpeg']
  
  # Comments
  acts_as_commentable
  
  # Tracker
  acts_as_activity :user
  
  # Tags
  acts_as_taggable
  
  
  # Favorite
  acts_as_favorite

	# Rating for Like or Unlike
  acts_as_rated :rating_range => 0..1, :with_stats_table => true
  
  # Named Scope
  scope :with_limit, :limit => 6
  scope :with_users, lambda {|u| {:conditions => "user_id IN(#{u})"}}
  scope :most_view, :conditions => "count_view > 0", :order => "count_view DESC"
  scope :previous, lambda { |att| {:conditions => ["musics.id < ?", att], :order => "id DESC"} }
  scope :nexts, lambda { |att| {:conditions => ["musics.id > ?", att], :order => "id DESC"} }
  
  # Fix the mime types. Make sure to require the mime-types gem
  def swfupload_file=(data)
    self.music_attach = data
  end
  
  def convert_seconds_to_time
    str = ""
    if length_in_seconds && length_in_seconds > 0
      total_minutes = length_in_seconds / 1.minutes
      seconds_in_last_minute = length_in_seconds - total_minutes.minutes.seconds
      str = "#{total_minutes}m #{seconds_in_last_minute}s"
    else
      str = ""
    end
  end

	def total_good
    self.ratings.count(:conditions => ["rating = ?", 1])
  end

  def total_bad
    self.ratings.count(:conditions => ["rating = ?", 0])
  end

	private
    def change_file_name
      unless music_attach_file_name.nil?
        self.music_attach.instance_write(:file_name, "#{music_attach_file_name.gsub("'", "`")}")
      end
    end
end

app/views/musics/_item_my_music.html.erb
<div class="musicL">
  <div class="photoImg"><%= link_to raw("<div>#{image_tag music_album.music_album_attach.url(:thumb)}</div>"), play_list_user_musics_url(current_user, :music_album_id => music_album) %></div>
  <div class="mostMSR">
    <div class="mostMSA"><%= link_to "", play_list_user_musics_url(current_user, :music_album_id => music_album), :class => "mostMSPlay" %><%= link_to "", new_user_music_url(current_user, :music_album_id => music_album), :class => "mostMSadd" %></div>
  </div>
  <div class="musicB">
    <div class="musicS" style="margin-top: -6px;"><%= pluralize(music_album.musics.size, "song") %></div>
    <div class="musicN"><%= link_to truncate(music_album.name, :length => 45, :omission => '...'), play_list_user_musics_url(current_user, :music_album_id => music_album) %></div>
  </div>
</div>

app/views/musics/_menu.html.erb
<%= link_to "Update Music Album", user_music_albums_url(current_user), :class => "slsShareS" %>
<%= link_to "Create a Music Album", create_form_user_musics_url(current_user), :remote => true %>

app/views/musics/_most_viewed.html.erb
<%
arr_user_id = []
arr_user_id << current_user.id
if current_user.user_friends
  current_user.user_friends.each do |friend|
    arr_user_id << friend.id if check_private_permission(current_user, friend, "my_musics")
  end
end
u = arr_user_id.join(", ")
most_viewed_music_albums = MusicAlbum.with_users(u).with_limit.most_view
%>

<div class="col300 slStory">
  <div class="col300in mostMS">
    <h1 class="col300Title">Most viewed music albums</h1>
    <% most_viewed_music_albums.each do |music_album| %>
      <div class="photoImg" style="margin-bottom: 16px">     
          <%= link_to raw("<div>#{image_tag music_album.music_album_attach.url(:thumb)}</div>"), play_list_user_musics_url(current_user, :music_album_id => music_album) %>      
        <span style="height: 30px; width: 85px; overflow: hidden; margin-top: -17px; position: absolute; word-wrap: break-word;"><%= truncate(music_album.name,:length => 20, :omission => '...') %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/musics/_music_action.html.erb
<div class="stoDbtm">
  <div class="AsDContBtm">
    <span class="btmComment"><a href="javascript:;" onclick="$('#form_comment').toggle('slow');">Comment</a></span>
    <span class="btmFav" id="item_favorite_<%= @music.id %>"><%= show_favorite_in_detail("Music", @music) %></span>
    <span class="btmAbuse"><%= show_report_abuse(@music) %></span>
  </div>
</div>

app/views/musics/_music_album_action.html.erb
<% if logged_in? %>
<div id="add_tag">
  <%= render :partial => "musics/form_add_tag" %>
</div>
<% end %>
<div class="stoDbtm">
  <div class="AsDContBtm">
    <span class="btmComment"><a href="javascript:;" onclick="$('#form_comment').toggle('slow');">Comment</a></span>
    <span class="btmFav" id="item_favorite_<%= @music_album.id %>"><%= show_favorite_in_detail("MusicAlbum", @music_album) %></span>
    <span class="btmAbuse"><%= show_report_abuse(@music_album) %></span>
    <% if logged_in? %>
		<span class="btmComment"><a href="javascript:;" onclick="$('form#form_tag_user').toggle('slow');">Let's Listen</a></span>
		<% end %>
    <span id="rate_pos"><%= render :partial => "music_albums/rating_action", :locals => {:post => @music_album, :controller_name => "music_albums"}%></span>
  </div>
</div>

app/views/musics/_select_musics.html.erb
<!--Alert-->
<div id="delete-dialog-message" title="Confirm delete" style="display:none;">
  <p>
    Really delete the highlighted element?
  </p>
</div>
<!--Alert-->
<div class="files">
  <%= form_for :music, :url => upload_user_musics_url(current_user), :html => { :class => "upload", :multipart => true, :id => "music_form" } do |f| %>
    <%= hidden_field_tag "music[music_album_id]", "" %>
    <%= file_field_tag "music[music_attach]", :multiple => true %>
    <div>
      Select musics
    </div>
  <% end %>
  <table class="upload_files" width="100%">
  </table>
  <div class="stoExBtm">
    <div class="stoExSave" id="create_bt">
      <a onclick="create_album();" href="javascript:;">Create</a>
    </div>
    <div class="stoExSave" id="start_uploads" style="display:none;">
      <a href="javascript:;" >Upload</a>
    </div>
    <div class="stoExCan"><a href="javascript:;" onclick="$('#create_a_album').hide();">Cancel</a></div>
  </div>
  <br/>
  <table class="download_files" width="100%">
  </table>
</div>
<script>
  $(document).ready(function(){
    $('#music_form').each(function(){
      // Fix for browsers which support multiple file selection but not the File API:
      // https://github.com/blueimp/jQuery-File-Upload/issues#issue/36
      if (typeof File === 'undefined') {
        $(this).find('input:file').each(function(){
          $(this).removeAttr('multiple') // Fix for Opera, which ignores just removing the multiple attribute:
          .replaceWith($(this).clone(true));
        });
      }
    }).fileUploadUI({
      uploadTable: $('.upload_files'),
      downloadTable: $('.download_files'),
      buildUploadRow: function(files, index){
        var fileNames;
        if (typeof index == 'number') {
          fileNames = files[index].name;
        }
        else {
          fileNames = '';
          for (i = 0; i < files.length; i += 1) {
            fileNames = fileNames + files[i].name + '<br>';
          }
        }
        var bt_upload = "";
        if ($('#music_music_album_id').val() != ""){
          bt_upload = '<td class="file_upload_start">' + '<button class="ui-state-default ui-corner-all" title="Start Upload">' + '<span class="ui-icon ui-icon-circle-arrow-e">Start Upload<\/span>' + '<\/button><\/td>';
        }else{
          bt_upload = '<td class="file_upload_start">' + '<button class="ui-state-default ui-corner-all" title="Start Upload" style="display:none;">' + '<span class="ui-icon ui-icon-circle-arrow-e">Start Upload<\/span>' + '<\/button><\/td>';
        }
        return $('<tr><td class="file_upload_preview_music"><\/td>' +
          '<td class="file_upload_title_music">' +
          fileNames +
          '<\/td>' +
          '<td class="file_upload_txt_title"><input type="text" title="Title" class="musicTitle" value="Title"><\/td>' +
          '<td class="file_upload_progress"><div><\/div><\/td>' +
          bt_upload +
          '<td class="file_upload_cancel">' +
          '<button class="ui-state-default ui-corner-all" title="Cancel">' +
          '<span class="ui-icon ui-icon-cancel">Cancel<\/span>' +
          '<\/button><\/td><\/tr>');
      },
      buildDownloadRow: function(file){
        return $('<tr id="file_' + file.id + '"><td>' + file.name + '<\/td>' +
          '<td class="file_delete"><button title="Delete" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-trash"></span></button></td>' +
          '<\/tr>');
      },
      beforeSend: function(event, files, index, xhr, handler, callBack){
        var regexp = /\.(mp3)|(wav)|(mpeg3)$/i;
        // Using the filename extension for our test,
        // as legacy browsers don't report the mime type
        if (!regexp.test(files[index].name)) {
          handler.uploadRow.find('.file_upload_progress').html('ONLY MP3 ALLOWED!');
          setTimeout(function(){
            handler.removeNode(handler.uploadRow);
          }, 10000);
          return;
        }
                    
        if (files[index].size > 10000000) {
          handler.uploadRow.find('.file_upload_progress').html('FILE TOO BIG!');
          setTimeout(function(){
            handler.removeNode(handler.uploadRow);
          }, 10000);
          return;
        }
                    
        handler.uploadRow.find('.file_upload_start button').click(function(){
          title = handler.uploadRow.find('.file_upload_txt_title input').val();
          if (title == "Title"){
            title = "";
          }
          handler.formData = {
            "music[title]": title,
            "music[music_album_id]": $('#music_music_album_id').val(),
            "authenticity_token": $('[name="authenticity_token"]').val()
          };
          callBack();
        });
      }
    });
  });
        
  $('#start_uploads').click(function(){
    $('.file_upload_start button').click();
  });
    	
  $('#cancel_uploads').click(function(){
    $('.file_upload_cancel button').click();
  });
		
  $('.file_delete button').live('click', function () {
    deleteFile(getKey($(this).closest('tr')));
    return false;
  });
			
  function deleteItem(node, url, callBack) {
    node.addClass('ui-state-highlight');
    $("#delete-dialog-message").dialog({
      modal: true,
      buttons: {
        Delete: function() {
          $.ajax({
            url: url,
            type: 'DELETE',
            success: function (data) {
              callBack(data);
            }
          });
        },
        Cancel: function() {
          $("#delete-dialog-message").dialog('close');
          node.removeClass('ui-state-highlight');
        }
      }
    });
  }
	
  function upload_files(){
    $('.file_upload_start button').click();
    $('#create_bt').hide();
    $('#start_uploads').show();
  }

  function deleteFile(key) {
    var path = "<%= user_musics_url(current_user)%>/" + key;
    var node = getFileNode(key);
    deleteItem(node, path, function (data) {
      node.fadeOut(function () {
        $("#delete-dialog-message").dialog('close');
        $(this).remove();
      });
    });
  }
		
  function getKey(node) {
    return node.attr('id').replace(/\w+?_/, '');
  }
			
  function getFileNode(key) {
    return $('#file_' + key);
  }

</script>
<style>
  .file_upload {
    position: relative;
    overflow: hidden;
    direction: ltr;
    cursor: pointer;
    text-align: center;
    color: #333;
    font-weight: bold;
    -moz-border-radius: 10px;
    -webkit-border-radius: 10px;
    border-radius: 10px;
    width: 110px;
    height: 25px;
    line-height: 25px;
    background: #E4E4E4;
    border: 1px solid limegreen;
  }
  .file_upload input {
    position: absolute;
    top: 0;
    right: 0;
    margin: 0;
    border: 300px solid transparent;
    opacity: 0;
    -ms-filter: 'alpha(opacity=0)';
    filter: alpha(opacity=0);
    -o-transform: translate(-300px, -300px) scale(10);
    -moz-transform: translate(-800px, 0) scale(10);
    cursor: pointer;
  }
  .file_upload_preview_music {
    height: 50px;
    width: 120px;
  }
  .file_upload_title_music {
    margin-left: 3px;
    overflow: hidden;
    position: absolute;
    white-space: nowrap;
    width: 448px;
  }
  .file_upload_progress div {
    height: 15px;
    width: 150px;
  }
  .file_upload_progress .ui-progressbar-value {
    background: url(/images/pbar-ani.gif);
  }
</style>

app/views/musics/create_playlist.html.erb
<playlist version='1' xmlns='http://xspf.org/ns/0/'>
  <title><%= @music_album.name %></title>
  <info><%= pluralize(@music_album.musics.size, "song") %></info>
  <image>-noimage.jpg</image>
  <trackList>
    <% @music_album.musics.each do |music| %>
      <track>
        <title><%= music.title %></title>
        <location><%= music.music_attach.url %></location>
        <album><%= @music_album.name %></album>
        <duration><%= music.length_in_seconds %></duration>
      </track>
    <% end %>
  </trackList>
</playlist>

app/views/musics/play_list.html.erb
<% content_for :menu_top_student_lounge do -%>
  <%= render :partial => '/shared/submenu' %>
<% end -%>

<div class="slStoryL">
  <div class="contDetL">
    <div class="contDetLin">
      <div class="inboxLeft">
        <div class="slsShare">
          <div class="slsShareL">
            <span>You are here:</span>
            <%= link_to "Musics", user_musics_url(current_user), :class => "slsShareLink" %>
            <a href="javascript:;" class="slsShareLinkL"><%= current_user == @music_album.user ? "Your musics" : "Friends shared musics" %></a>
          </div>
          <div class="slsShareR">
            <%= render :partial => "menu" %>
          </div>
        </div>
        <%= display_flash_messages_with_raw %>
        <%= render :partial => "expand_create_music_album" %>
        <div class="stoDet phoD">
          <div class="AsDcomImg">
            <%= show_image_user_post(@music_album.user) %>
          </div>
          <div class="stoDetR">
            <div class="stoDetRT">
              <%= @music_album.user.full_name %>: <%= @music_album.name %>
            </div>
          </div>
        </div>
        <div class="musicVideo" id="playlist_list">
          <% if @music_album.music_album_attach %>
            <div class="photoImg">
              <%= image_tag @music_album.music_album_attach.url(:thumb) %>
            </div>
          <% end %>
          <%= render :partial => "music_playlist" %>
        </div>
        <%= render :partial => "music_album_action" %>
        <%= show_post_comments(@music_album) %>
        <div class="goback" id="go_back">
          <%= show_go_back %>
        </div>
        <div class="AsDOr">
          <h1 class="titleH1">Another music albums</h1>
          <% @another_music_albums.each do |mb| %>
            <div class="AsDOrItem">
              <%= link_to mb.name, play_list_user_musics_url(current_user, :music_album_id => mb) %>
            </div>
          <% end %>
        </div>
        <div class="goTop">
          <a href="javascript:;" onclick="goToByScroll('top_page')">Top</a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="contMainR">
  <!--Most Viewed-->
  <%= render :partial => "most_viewed" %>
  <!--Most Viewed-->
	<div id="on_this_music">
  <%= render :partial => "lets_listen" %>
	</div>
  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->
</div>

app/views/musics/show.html.erb
<% content_for :menu_top_student_lounge do -%>
  <%= render :partial => '/shared/submenu' %>
<% end -%>
<div class="slStoryL">
  <div class="contDetL">
    <div class="contDetLin">
      <div class="inboxLeft">
        <div class="slsShare">
          <div class="slsShareL">
            <span>You are here:</span>
            <%= link_to "Musics", user_musics_url(current_user), :class => "slsShareLink" %>
            <a href="javascript:;" class="slsShareLinkL"><%= current_user == @music.user ? "Your musics" : "Friends shared musics" %></a>
          </div>
          <div class="slsShareR">
            <%= render :partial => "menu" %>
          </div>
        </div>
        <%= display_flash_messages_with_raw %>
        <%= render :partial => "expand_create_music_album" %>
        <div class="stoDet phoD">
          <div class="AsDcomImg">
            <%= show_image_user_post(@music.user) %>
          </div>
          <div class="stoDetR">
            <div class="stoDetRT">
              <%= @music.user.full_name %>: <%= link_to @music.music_album.name, play_list_user_musics_url(current_user, :music_album_id => @music.music_album) %>
            </div>
          </div>
        </div>
        <div class="onThisBtm">
          <div class="stoPre">
            <%= link_to "", user_music_path(current_user, @prev) if @prev %>
          </div>
          <div class="stoNext">
            <%= link_to "", user_music_path(current_user, @next) if @next %>
          </div>
        </div>
        <div class="AsDOr RePho">
          <div class="musicVideo" id="playlist_list">
            <% if @music.music_album.music_album_attach %>
              <div class="photoImg">
                <%= image_tag @music.music_album.music_album_attach.url(:thumb) %>
              </div>
            <% end %>
            <div id="playlist_<%= @music.id %>">
              <div href="<%= @music.music_attach.url %>" style="width: 400px;" class="item">
                <div>
                  <div class="btn play">
                  </div>
                  <div class="title">
                    <b><%= @music.music_attach_file_name %></b>
                  </div>
                </div>
                <div class="player inactive"></div>
              </div>
            </div>
            <script type="text/javascript">
              $(document).ready(function(){
                $("#playlist_list").playlist({
                  playerurl: "/swfs/drplayer.swf"
                });
              });
            </script>
          </div>
        </div>
        <%= render :partial => "music_action" %>
        <%= show_post_comments(@music) %>
        <div class="goback" id="go_back">
          <%= show_go_back %>
        </div>
        <div class="goTop">
          <a href="javascript:;" onclick="goToByScroll('top_page')">Top</a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="contMainR">
  <!--Most Viewed-->
  <%= render :partial => "on_this_music" %>
  <!--Most Viewed-->
  <!--Ads-->
  <%= render :partial => "ads/show_vertical_ads" %>
  <!--Ads-->
</div>